<?php

use Illuminate\Database\Seeder;

class EcarrerPortalsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('ecarrer_portals')->delete();
        
        \DB::table('ecarrer_portals')->insert(array (
            0 => 
            array (
                'id' => 1,
                'title_en' => 'Life At Banglalink Changed',
                'title_bn' => 'Life At Banglalink bangla',
                'slug' => 'life_at_banglalink_changed',
                'description_en' => NULL,
                'description_bn' => NULL,
                'image' => NULL,
                'video' => NULL,
                'alt_text' => NULL,
                'category' => 'life_at_bl_general',
                'route_slug' => 'life-at-banglalink/general',
                'category_type' => 'news_on_top',
                'additional_info' => NULL,
                'is_active' => 1,
                'has_items' => 1,
                'is_default' => 0,
                'created_at' => '2020-02-04 11:53:08',
                'updated_at' => '2020-02-20 11:33:10',
                'deleted_at' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'title_en' => 'Commercial',
                'title_bn' => 'Commercial Bangla',
                'slug' => 'commercial',
                'description_en' => NULL,
                'description_bn' => NULL,
                'image' => NULL,
                'video' => NULL,
                'alt_text' => NULL,
                'category' => 'life_at_bl_teams',
                'route_slug' => 'life-at-banglalink/teams',
                'category_type' => 'teams_tab_section',
                'additional_info' => NULL,
                'is_active' => 1,
                'has_items' => 1,
                'is_default' => 0,
                'created_at' => '2020-02-04 11:55:01',
                'updated_at' => '2020-02-24 08:25:05',
                'deleted_at' => '2020-02-24 08:25:05',
            ),
            2 => 
            array (
                'id' => 6,
                'title_en' => 'Values',
                'title_bn' => 'মানগুলি',
                'slug' => 'values',
                'description_en' => NULL,
                'description_bn' => NULL,
                'image' => NULL,
                'video' => NULL,
                'alt_text' => NULL,
                'category' => 'life_at_bl_general',
                'route_slug' => 'life-at-banglalink/general',
                'category_type' => 'values_section',
                'additional_info' => NULL,
                'is_active' => 1,
                'has_items' => 1,
                'is_default' => 0,
                'created_at' => '2020-02-05 10:47:58',
                'updated_at' => '2020-02-17 14:05:56',
                'deleted_at' => NULL,
            ),
            3 => 
            array (
                'id' => 7,
                'title_en' => 'We At campus',
                'title_bn' => 'আমরা ক্যাম্পাসে',
                'slug' => 'we_at_campus',
                'description_en' => NULL,
                'description_bn' => NULL,
                'image' => NULL,
                'video' => NULL,
                'alt_text' => NULL,
                'category' => 'life_at_bl_general',
                'route_slug' => 'life-at-banglalink/general',
                'category_type' => 'campus_section',
                'additional_info' => NULL,
                'is_active' => 1,
                'has_items' => 1,
                'is_default' => 0,
                'created_at' => '2020-02-05 10:48:41',
                'updated_at' => '2020-02-17 14:06:06',
                'deleted_at' => NULL,
            ),
            4 => 
            array (
                'id' => 9,
                'title_en' => 'Photo Gallery slider',
                'title_bn' => 'Irure consequatur i',
                'slug' => 'photo_gallery_slider',
                'description_en' => NULL,
                'description_bn' => NULL,
                'image' => NULL,
                'video' => NULL,
                'alt_text' => NULL,
                'category' => 'programs_photogallery',
                'route_slug' => 'programs/photogallery',
                'category_type' => 'sap',
                'additional_info' => '{"sider_info": {"sliding_speed": "10"}}',
                'is_active' => 0,
                'has_items' => 1,
                'is_default' => 0,
                'created_at' => '2020-02-05 14:06:43',
                'updated_at' => '2020-02-24 08:42:27',
                'deleted_at' => NULL,
            ),
            5 => 
            array (
                'id' => 10,
                'title_en' => 'Brain Station 23',
                'title_bn' => 'ব্রেন স্টেশন  ২৩',
                'slug' => 'brain_station_23',
                'description_en' => 'To Be A Pioneer; Working At The Frontier To Unlock New Opportunities For Customers As They Navigate The Digital World.To Be A Pioneer; Working At The Frontier To Unlock New Opportunities For Customers.',
                'description_bn' => 'টু আ পাইওনিয়ার; ডিজিটাল ওয়ার্ল্ড নেভিগেট করার সাথে সাথে গ্রাহকদের জন্য নতুন সুযোগগুলি আনলক করতে সীমান্তে কাজ করা Tপ্রিয় হয়ে উঠুন; গ্রাহকদের জন্য নতুন সুযোগ আনলক করতে সীমান্তে কাজ করা।',
                'image' => NULL,
                'video' => 'https://www.youtube.com/embed/ecp7ZwwNAAM',
                'alt_text' => 'Esse incidunt veli',
                'category' => 'vacancy_pioneer',
                'route_slug' => 'vacancy/pioneer',
                'category_type' => 'bottom_news_media',
                'additional_info' => NULL,
                'is_active' => 1,
                'has_items' => 0,
                'is_default' => 0,
                'created_at' => '2020-02-05 14:23:23',
                'updated_at' => '2020-02-19 09:39:10',
                'deleted_at' => NULL,
            ),
            6 => 
            array (
                'id' => 11,
                'title_en' => 'First Box',
                'title_bn' => 'প্রথম বক্স',
                'slug' => 'first_box',
                'description_en' => 'Any Alarm Information Is Transmitted In The Form Of MMS, SMS, Calls, E-Mails Or An Alarm Receiving Center. Any Alarm Information Is Transmitted In The Form Of MMS, SMS, Calls, E-Mails Or An Alarm Receiving Center.',
                'description_bn' => 'যে কোনও অ্যালার্ম তথ্য এমএমএস, এসএমএস, কল, ই-মেল বা একটি বিপদ প্রাপ্তি কেন্দ্রের আকারে প্রেরণ করা হয়। যে কোনও অ্যালার্ম তথ্য এমএমএস, এসএমএস, কল, ই-মেল বা একটি বিপদ প্রাপ্তি কেন্দ্রের আকারে প্রেরণ করা হয়।',
                'image' => 'assetlite/images/ecarrer/general_section/bMihFKRm6Cf9asGNQtAerenYwm3XoHQKO1jbwrkf.png',
                'video' => NULL,
                'alt_text' => 'In doloremque natus',
                'category' => 'vacancy_viconbox',
                'route_slug' => 'vacancy/viconbox',
                'category_type' => NULL,
                'additional_info' => NULL,
                'is_active' => 1,
                'has_items' => 0,
                'is_default' => 0,
                'created_at' => '2020-02-05 14:23:31',
                'updated_at' => '2020-02-19 10:00:34',
                'deleted_at' => NULL,
            ),
            7 => 
            array (
                'id' => 12,
                'title_en' => 'Contact Us',
                'title_bn' => 'যোগাযোগ করুন',
                'slug' => 'contact_us',
                'description_en' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque ultrices justo ut arcu vehicula, non elementum nibh tristique. Donec lacus est, consectetur eget facilisis a ENGLISH',
                'description_bn' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque ultrices justo ut arcu vehicula, non elementum nibh tristique. Donec lacus est, consectetur eget facilisis a BANGLA',
                'image' => NULL,
                'video' => NULL,
                'alt_text' => NULL,
                'category' => 'life_at_bl_contact',
                'route_slug' => 'life-at-banglalink/contact',
                'category_type' => 'contact_us',
                'additional_info' => NULL,
                'is_active' => 1,
                'has_items' => 0,
                'is_default' => 0,
                'created_at' => '2020-02-05 14:39:40',
                'updated_at' => '2020-02-17 10:00:21',
                'deleted_at' => NULL,
            ),
            8 => 
            array (
                'id' => 13,
                'title_en' => 'Connect Us At Social Media',
                'title_bn' => 'আমাদের সাথে যোগাযোগ করুন সোশ্যাল মিডিয়ার মাধ্যমে',
                'slug' => 'connect_us_at_social_media',
                'description_en' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. ENGLISH',
                'description_bn' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. বাংলা',
                'image' => NULL,
                'video' => NULL,
                'alt_text' => NULL,
                'category' => 'life_at_bl_contact',
                'route_slug' => 'life-at-banglalink/contact',
                'category_type' => 'connect_us_social',
                'additional_info' => NULL,
                'is_active' => 1,
                'has_items' => 1,
                'is_default' => 0,
                'created_at' => '2020-02-05 14:39:56',
                'updated_at' => '2020-02-17 10:01:48',
                'deleted_at' => NULL,
            ),
            9 => 
            array (
                'id' => 14,
                'title_en' => 'Batch 1',
                'title_bn' => 'zadasdsads',
                'slug' => 'batch_1',
                'description_en' => NULL,
                'description_bn' => NULL,
                'image' => NULL,
                'video' => NULL,
                'alt_text' => NULL,
                'category' => 'programs_sapbatches',
                'route_slug' => 'programs/sapbatches',
                'category_type' => 'batch_content',
                'additional_info' => NULL,
                'is_active' => 1,
                'has_items' => 1,
                'is_default' => 0,
                'created_at' => '2020-02-06 05:20:45',
                'updated_at' => '2020-02-24 09:15:25',
                'deleted_at' => NULL,
            ),
            10 => 
            array (
                'id' => 15,
                'title_en' => 'Life At Banglalink',
                'title_bn' => 'লাইফ এট  বাংলালিংক',
                'slug' => 'life-at-banglalink',
                'description_en' => NULL,
                'description_bn' => NULL,
                'image' => 'assetlite/images/ecarrer/general_section/gtenqfuci3KE58rIqdXDF0lpeEk17JBeaIoJkBip.jpeg',
                'video' => NULL,
                'alt_text' => 'Banner Image',
                'category' => 'life_at_bl_topbanner',
                'route_slug' => 'life-at-banglalink/topbanner',
                'category_type' => 'life_at_banglalink',
                'additional_info' => NULL,
                'is_active' => 1,
                'has_items' => 0,
                'is_default' => 0,
                'created_at' => '2020-02-06 07:01:56',
                'updated_at' => '2020-02-24 06:51:09',
                'deleted_at' => NULL,
            ),
            11 => 
            array (
                'id' => 16,
                'title_en' => 'Programs',
                'title_bn' => 'প্রোগ্রামস',
                'slug' => 'programs',
                'description_en' => NULL,
                'description_bn' => NULL,
                'image' => 'assetlite/images/ecarrer/general_section/5GKQbeED1jIMBvlHqBVQ1qsfwc4xM695821Q4lgQ.jpeg',
                'video' => NULL,
                'alt_text' => 'programs',
                'category' => 'life_at_bl_topbanner',
                'route_slug' => 'life-at-banglalink/topbanner',
                'category_type' => 'programs',
                'additional_info' => NULL,
                'is_active' => 1,
                'has_items' => 0,
                'is_default' => 0,
                'created_at' => '2020-02-06 07:01:56',
                'updated_at' => '2020-02-24 06:51:15',
                'deleted_at' => NULL,
            ),
            12 => 
            array (
                'id' => 17,
                'title_en' => 'Vacancy',
                'title_bn' => 'ভেকেন্সি',
                'slug' => 'vacancy',
                'description_en' => NULL,
                'description_bn' => NULL,
                'image' => 'assetlite/images/ecarrer/general_section/hDJzAXjkcYE9pRq8eLtAruxyJ9xzNYVvlV0N8ibh.jpeg',
                'video' => NULL,
                'alt_text' => 'vacancy',
                'category' => 'life_at_bl_topbanner',
                'route_slug' => 'life-at-banglalink/topbanner',
                'category_type' => 'vacancy',
                'additional_info' => NULL,
                'is_active' => 1,
                'has_items' => 0,
                'is_default' => 0,
                'created_at' => '2020-02-06 07:01:56',
                'updated_at' => '2020-02-24 06:51:21',
                'deleted_at' => NULL,
            ),
            13 => 
            array (
                'id' => 18,
                'title_en' => 'Technology',
                'title_bn' => 'Technology Bangla',
                'slug' => 'technology',
                'description_en' => NULL,
                'description_bn' => NULL,
                'image' => NULL,
                'video' => NULL,
                'alt_text' => NULL,
                'category' => 'life_at_bl_teams',
                'route_slug' => 'life-at-banglalink/teams',
                'category_type' => 'teams_tab_section',
                'additional_info' => NULL,
                'is_active' => 1,
                'has_items' => 1,
                'is_default' => 0,
                'created_at' => '2020-02-06 07:20:54',
                'updated_at' => '2020-02-24 08:25:08',
                'deleted_at' => '2020-02-24 08:25:08',
            ),
            14 => 
            array (
                'id' => 19,
                'title_en' => 'Enablers',
                'title_bn' => NULL,
                'slug' => 'enablers',
                'description_en' => NULL,
                'description_bn' => NULL,
                'image' => NULL,
                'video' => NULL,
                'alt_text' => NULL,
                'category' => 'life_at_bl_teams',
                'route_slug' => 'life-at-banglalink/teams',
                'category_type' => 'teams_tab_section',
                'additional_info' => NULL,
                'is_active' => 1,
                'has_items' => 1,
                'is_default' => 0,
                'created_at' => '2020-02-06 07:33:31',
                'updated_at' => '2020-02-24 08:25:11',
                'deleted_at' => '2020-02-24 08:25:11',
            ),
            15 => 
            array (
                'id' => 20,
                'title_en' => 'SAP News Section',
                'title_bn' => NULL,
                'slug' => 'sap_news_section',
                'description_en' => NULL,
                'description_bn' => NULL,
                'image' => NULL,
                'video' => NULL,
                'alt_text' => NULL,
                'category' => 'programs_progeneral',
                'route_slug' => 'programs/progeneral',
                'category_type' => 'ennovators',
                'additional_info' => '{"additional_type": "programs_news_section"}',
                'is_active' => 1,
                'has_items' => 1,
                'is_default' => 0,
                'created_at' => '2020-02-06 07:36:38',
                'updated_at' => '2020-02-24 08:59:59',
                'deleted_at' => NULL,
            ),
            16 => 
            array (
                'id' => 21,
                'title_en' => 'Diversity Changed',
                'title_bn' => 'Diversity Bangla',
                'slug' => 'diversity_changed',
                'description_en' => 'At Banglalink, you’ll find diverse career paths woven across our businesses and in locations all over the world. test',
                'description_bn' => 'বাংলালিংকে, আপনি আমাদের ব্যবসায়ের জুড়ে এবং সারা বিশ্বের অবস্থানগুলিতে বোনা বিভিন্ন ক্যারিয়ারের পথ খুঁজে পাবেন।',
                'image' => NULL,
                'video' => NULL,
                'alt_text' => NULL,
                'category' => 'life_at_bl_diversity',
                'route_slug' => 'life-at-banglalink/diversity',
                'category_type' => NULL,
                'additional_info' => NULL,
                'is_active' => 1,
                'has_items' => 1,
                'is_default' => 0,
                'created_at' => '2020-02-06 10:04:23',
                'updated_at' => '2020-02-24 08:29:49',
                'deleted_at' => '2020-02-24 08:29:49',
            ),
            17 => 
            array (
                'id' => 22,
                'title_en' => 'Events & Activities',
                'title_bn' => 'Events & Activities Bangla',
                'slug' => 'events_&_activities',
                'description_en' => NULL,
                'description_bn' => NULL,
                'image' => NULL,
                'video' => NULL,
                'alt_text' => NULL,
                'category' => 'life_at_bl_events',
                'route_slug' => 'life-at-banglalink/events',
                'category_type' => NULL,
                'additional_info' => '{"sider_info": {"sliding_speed": "5"}}',
                'is_active' => 1,
                'has_items' => 1,
                'is_default' => 1,
                'created_at' => '2020-02-06 10:08:07',
                'updated_at' => '2020-02-17 14:02:30',
                'deleted_at' => NULL,
            ),
            18 => 
            array (
                'id' => 23,
                'title_en' => 'Testimonials',
                'title_bn' => 'Testimonials Bangla',
                'slug' => 'testimonials',
                'description_en' => NULL,
                'description_bn' => NULL,
                'image' => NULL,
                'video' => NULL,
                'alt_text' => NULL,
                'category' => 'programs_progeneral',
                'route_slug' => 'programs/progeneral',
                'category_type' => 'aip',
                'additional_info' => '{"additional_type": "programs_testimonial"}',
                'is_active' => 1,
                'has_items' => 1,
                'is_default' => 0,
                'created_at' => '2020-02-06 10:14:04',
                'updated_at' => '2020-02-24 09:00:05',
                'deleted_at' => NULL,
            ),
            19 => 
            array (
                'id' => 24,
                'title_en' => 'Box icon sections for Ennovators',
                'title_bn' => NULL,
                'slug' => 'box_icon_sections_for_ennovators',
                'description_en' => NULL,
                'description_bn' => NULL,
                'image' => NULL,
                'video' => NULL,
                'alt_text' => NULL,
                'category' => 'programs_proiconbox',
                'route_slug' => 'programs/proiconbox',
                'category_type' => 'ennovators',
                'additional_info' => NULL,
                'is_active' => 0,
                'has_items' => 1,
                'is_default' => 0,
                'created_at' => '2020-02-06 10:17:18',
                'updated_at' => '2020-02-24 08:48:16',
                'deleted_at' => NULL,
            ),
            20 => 
            array (
                'id' => 25,
                'title_en' => 'Previous Batches',
                'title_bn' => 'Previous Batches Bangla',
                'slug' => 'previous_batches',
                'description_en' => NULL,
                'description_bn' => NULL,
                'image' => NULL,
                'video' => NULL,
                'alt_text' => NULL,
                'category' => 'programs_sapbatches',
                'route_slug' => 'programs/sapbatches',
                'category_type' => 'batch_title',
                'additional_info' => NULL,
                'is_active' => 1,
                'has_items' => 0,
                'is_default' => 0,
                'created_at' => '2020-02-06 10:22:08',
                'updated_at' => '2020-02-24 09:15:30',
                'deleted_at' => NULL,
            ),
            21 => 
            array (
                'id' => 26,
                'title_en' => 'asd',
                'title_bn' => 'asd',
                'slug' => 'asd',
                'description_en' => NULL,
                'description_bn' => NULL,
                'image' => NULL,
                'video' => NULL,
                'alt_text' => NULL,
                'category' => 'programs_progeneral',
                'route_slug' => 'programs/progeneral',
                'category_type' => 'aip',
                'additional_info' => '{"additional_type": "programs_news_section"}',
                'is_active' => 1,
                'has_items' => 1,
                'is_default' => 0,
                'created_at' => '2020-02-09 06:32:30',
                'updated_at' => '2020-02-24 09:00:10',
                'deleted_at' => NULL,
            ),
            22 => 
            array (
                'id' => 27,
                'title_en' => 'Teams',
                'title_bn' => 'Teams Tile bangla',
                'slug' => 'teams',
                'description_en' => NULL,
                'description_bn' => NULL,
                'image' => NULL,
                'video' => NULL,
                'alt_text' => NULL,
                'category' => 'life_at_bl_teams',
                'route_slug' => 'life-at-banglalink/teams',
                'category_type' => 'teams_title',
                'additional_info' => NULL,
                'is_active' => 1,
                'has_items' => 0,
                'is_default' => 0,
                'created_at' => '2020-02-11 10:02:54',
                'updated_at' => '2020-02-24 08:25:13',
                'deleted_at' => '2020-02-24 08:25:13',
            ),
            23 => 
            array (
                'id' => 28,
                'title_en' => 'How We Hire',
                'title_bn' => 'কিভাবে আমরা ভাড়া করি',
                'slug' => 'how_we_hire',
                'description_en' => 'To Be A Pioneer; Working At The Frontier To Unlock New Opportunities For Customers As They Navigate The Digital World.To Be A Pioneer; Working At The Frontier To Unlock New Opportunities For Customers.',
                'description_bn' => 'টু আ পাইওনিয়ার; ডিজিটাল ওয়ার্ল্ড নেভিগেট করার সাথে সাথে গ্রাহকদের জন্য নতুন সুযোগগুলি আনলক করতে সীমান্তে কাজ করা Tপ্রিয় হয়ে উঠুন; গ্রাহকদের জন্য নতুন সুযোগ আনলক করতে সীমান্তে কাজ করা।',
                'image' => 'assetlite/images/ecarrer/general_section/ufEkp1BWRft0b0GDlsBGQbdovlC2kWAfhTE7KPA7.png',
                'video' => NULL,
                'alt_text' => 'Alter text',
                'category' => 'vacancy_pioneer',
                'route_slug' => 'vacancy/pioneer',
                'category_type' => 'how_we_hire',
                'additional_info' => NULL,
                'is_active' => 1,
                'has_items' => 0,
                'is_default' => 0,
                'created_at' => '2020-02-12 07:30:24',
                'updated_at' => '2020-02-19 09:31:03',
                'deleted_at' => NULL,
            ),
            24 => 
            array (
                'id' => 29,
                'title_en' => 'Job Offers',
                'title_bn' => 'Job Offers Bangla',
                'slug' => 'job_offers',
                'description_en' => NULL,
                'description_bn' => NULL,
                'image' => NULL,
                'video' => NULL,
                'alt_text' => NULL,
                'category' => 'vacancy_pioneer',
                'route_slug' => 'vacancy/pioneer',
                'category_type' => 'job_offers_title',
                'additional_info' => NULL,
                'is_active' => 0,
                'has_items' => 0,
                'is_default' => 0,
                'created_at' => '2020-02-12 07:31:14',
                'updated_at' => '2020-02-24 06:56:25',
                'deleted_at' => NULL,
            ),
            25 => 
            array (
                'id' => 30,
                'title_en' => 'Second Box',
                'title_bn' => 'দ্বিতীয় বাক্স',
                'slug' => 'second_box',
                'description_en' => 'Any Alarm Information Is Transmitted In The Form Of MMS, SMS, Calls, E-Mails Or An Alarm Receiving Center. Any Alarm Information Is Transmitted In The Form Of MMS, SMS, Calls, E-Mails Or An Alarm Receiving Center.',
                'description_bn' => 'যে কোনও অ্যালার্ম তথ্য এমএমএস, এসএমএস, কল, ই-মেল বা একটি বিপদ প্রাপ্তি কেন্দ্রের আকারে প্রেরণ করা হয়। যে কোনও অ্যালার্ম তথ্য এমএমএস, এসএমএস, কল, ই-মেল বা একটি বিপদ প্রাপ্তি কেন্দ্রের আকারে প্রেরণ করা হয়।',
                'image' => 'assetlite/images/ecarrer/general_section/6GjW5ftn2tP6vPjwHurhnMzLgoKNA5cuosG2XGcT.png',
                'video' => NULL,
                'alt_text' => 'Banner Image',
                'category' => 'vacancy_viconbox',
                'route_slug' => 'vacancy/viconbox',
                'category_type' => NULL,
                'additional_info' => NULL,
                'is_active' => 1,
                'has_items' => 0,
                'is_default' => 0,
                'created_at' => '2020-02-12 07:32:47',
                'updated_at' => '2020-02-19 10:00:43',
                'deleted_at' => NULL,
            ),
            26 => 
            array (
                'id' => 31,
                'title_en' => 'Third Box',
                'title_bn' => 'তৃতীয় বাক্স',
                'slug' => 'third_box',
                'description_en' => 'Any Alarm Information Is Transmitted In The Form Of MMS, SMS, Calls, E-Mails Or An Alarm Receiving Center. Any Alarm Information Is Transmitted In The Form Of MMS, SMS, Calls, E-Mails Or An Alarm Receiving Center.',
                'description_bn' => 'যে কোনও অ্যালার্ম তথ্য এমএমএস, এসএমএস, কল, ই-মেল বা একটি বিপদ প্রাপ্তি কেন্দ্রের আকারে প্রেরণ করা হয়। যে কোনও অ্যালার্ম তথ্য এমএমএস, এসএমএস, কল, ই-মেল বা একটি বিপদ প্রাপ্তি কেন্দ্রের আকারে প্রেরণ করা হয়।',
                'image' => 'assetlite/images/ecarrer/general_section/P0naZ6OJ99nB1iopdkkYVYjoYV8W2dJnkD76OMEs.png',
                'video' => NULL,
                'alt_text' => 'Alter text',
                'category' => 'vacancy_viconbox',
                'route_slug' => 'vacancy/viconbox',
                'category_type' => NULL,
                'additional_info' => NULL,
                'is_active' => 1,
                'has_items' => 0,
                'is_default' => 0,
                'created_at' => '2020-02-12 07:33:08',
                'updated_at' => '2020-02-19 10:00:52',
                'deleted_at' => NULL,
            ),
            27 => 
            array (
                'id' => 34,
                'title_en' => 'Steps',
                'title_bn' => 'Steps sections Bangla',
                'slug' => 'steps',
                'description_en' => NULL,
                'description_bn' => NULL,
                'image' => NULL,
                'video' => NULL,
                'alt_text' => NULL,
                'category' => 'programs_progeneral',
                'route_slug' => 'programs/progeneral',
                'category_type' => 'ennovators',
                'additional_info' => '{"additional_type": "programs_steps"}',
                'is_active' => 1,
                'has_items' => 1,
                'is_default' => 0,
                'created_at' => '2020-02-13 12:31:33',
                'updated_at' => '2020-02-24 09:00:15',
                'deleted_at' => NULL,
            ),
            28 => 
            array (
                'id' => 35,
                'title_en' => 'Previous Batches',
                'title_bn' => 'Previous Batches Bangla',
                'slug' => 'previous_batches',
                'description_en' => NULL,
                'description_bn' => NULL,
                'image' => NULL,
                'video' => NULL,
                'alt_text' => NULL,
                'category' => 'programs_ennovatorbatches',
                'route_slug' => 'programs/ennovatorbatches',
                'category_type' => 'batch_title',
                'additional_info' => NULL,
                'is_active' => 1,
                'has_items' => 0,
                'is_default' => 0,
                'created_at' => '2020-02-13 12:39:03',
                'updated_at' => '2020-02-24 09:15:00',
                'deleted_at' => NULL,
            ),
            29 => 
            array (
                'id' => 36,
                'title_en' => 'Batch 1',
                'title_bn' => 'Bantch 1 Bangla',
                'slug' => 'batch_1',
                'description_en' => NULL,
                'description_bn' => NULL,
                'image' => NULL,
                'video' => NULL,
                'alt_text' => NULL,
                'category' => 'programs_ennovatorbatches',
                'route_slug' => 'programs/ennovatorbatches',
                'category_type' => 'batch_content',
                'additional_info' => NULL,
                'is_active' => 1,
                'has_items' => 1,
                'is_default' => 0,
                'created_at' => '2020-02-13 12:39:41',
                'updated_at' => '2020-02-24 09:15:05',
                'deleted_at' => NULL,
            ),
            30 => 
            array (
                'id' => 37,
                'title_en' => 'Batch 2',
                'title_bn' => 'title of the News 02 Bangla',
                'slug' => 'batch_2',
                'description_en' => NULL,
                'description_bn' => NULL,
                'image' => NULL,
                'video' => NULL,
                'alt_text' => NULL,
                'category' => 'programs_ennovatorbatches',
                'route_slug' => 'programs/ennovatorbatches',
                'category_type' => 'batch_content',
                'additional_info' => NULL,
                'is_active' => 1,
                'has_items' => 1,
                'is_default' => 0,
                'created_at' => '2020-02-13 12:41:13',
                'updated_at' => '2020-02-24 09:15:17',
                'deleted_at' => NULL,
            ),
            31 => 
            array (
                'id' => 38,
                'title_en' => 'Events',
                'title_bn' => 'Events Bangla',
                'slug' => 'events',
                'description_en' => NULL,
                'description_bn' => NULL,
                'image' => NULL,
                'video' => NULL,
                'alt_text' => NULL,
                'category' => 'programs_progeneral',
                'route_slug' => 'programs/progeneral',
                'category_type' => 'ennovators',
                'additional_info' => '{"additional_type": "programs_events"}',
                'is_active' => 1,
                'has_items' => 1,
                'is_default' => 0,
                'created_at' => '2020-02-13 12:42:55',
                'updated_at' => '2020-02-24 09:00:20',
                'deleted_at' => NULL,
            ),
            32 => 
            array (
                'id' => 39,
                'title_en' => 'Photo Gallery',
                'title_bn' => 'Photo Gallery bangla',
                'slug' => 'photo_gallery',
                'description_en' => NULL,
                'description_bn' => NULL,
                'image' => NULL,
                'video' => NULL,
                'alt_text' => NULL,
                'category' => 'programs_photogallery',
                'route_slug' => 'programs/photogallery',
                'category_type' => 'ennovators',
                'additional_info' => '{"sider_info": {"sliding_speed": "10"}}',
                'is_active' => 0,
                'has_items' => 1,
                'is_default' => 0,
                'created_at' => '2020-02-13 12:47:06',
                'updated_at' => '2020-02-24 08:42:32',
                'deleted_at' => NULL,
            ),
            33 => 
            array (
                'id' => 40,
                'title_en' => 'test',
                'title_bn' => 'test',
                'slug' => 'test',
                'description_en' => NULL,
                'description_bn' => NULL,
                'image' => NULL,
                'video' => NULL,
                'alt_text' => NULL,
                'category' => 'life_at_bl_teams',
                'route_slug' => 'life-at-banglalink/teams',
                'category_type' => 'teams_title',
                'additional_info' => NULL,
                'is_active' => 1,
                'has_items' => 0,
                'is_default' => 0,
                'created_at' => '2020-02-17 05:08:34',
                'updated_at' => '2020-02-17 06:06:56',
                'deleted_at' => '2020-02-17 06:06:56',
            ),
            34 => 
            array (
                'id' => 41,
                'title_en' => 'test',
                'title_bn' => 'test',
                'slug' => 'test',
                'description_en' => NULL,
                'description_bn' => NULL,
                'image' => NULL,
                'video' => NULL,
                'alt_text' => NULL,
                'category' => 'life_at_bl_teams',
                'route_slug' => 'life-at-banglalink/teams',
                'category_type' => 'teams_tab_section',
                'additional_info' => NULL,
                'is_active' => 1,
                'has_items' => 1,
                'is_default' => 0,
                'created_at' => '2020-02-17 05:14:17',
                'updated_at' => '2020-02-17 06:00:22',
                'deleted_at' => '2020-02-17 06:00:22',
            ),
            35 => 
            array (
                'id' => 42,
                'title_en' => 'test',
                'title_bn' => 'test',
                'slug' => 'test',
                'description_en' => NULL,
                'description_bn' => NULL,
                'image' => NULL,
                'video' => NULL,
                'alt_text' => NULL,
                'category' => 'life_at_bl_teams',
                'route_slug' => 'life-at-banglalink/teams',
                'category_type' => 'teams_tab_section',
                'additional_info' => NULL,
                'is_active' => 1,
                'has_items' => 1,
                'is_default' => 0,
                'created_at' => '2020-02-17 05:59:47',
                'updated_at' => '2020-02-17 06:00:18',
                'deleted_at' => '2020-02-17 06:00:18',
            ),
            36 => 
            array (
                'id' => 43,
                'title_en' => 'arawrfasfasfafwfwqwrweweqweqweqweqwe',
                'title_bn' => NULL,
                'slug' => 'arawrfasfasfafwfwqwrweweqweqweqweqwe',
                'description_en' => NULL,
                'description_bn' => NULL,
                'image' => NULL,
                'video' => NULL,
                'alt_text' => NULL,
                'category' => 'life_at_bl_teams',
                'route_slug' => 'life-at-banglalink/teams',
                'category_type' => 'teams_tab_section',
                'additional_info' => NULL,
                'is_active' => 1,
                'has_items' => 1,
                'is_default' => 0,
                'created_at' => '2020-02-17 05:59:59',
                'updated_at' => '2020-02-17 06:00:13',
                'deleted_at' => '2020-02-17 06:00:13',
            ),
            37 => 
            array (
                'id' => 44,
                'title_en' => 'aset',
                'title_bn' => 'aet',
                'slug' => 'aset',
                'description_en' => NULL,
                'description_bn' => NULL,
                'image' => NULL,
                'video' => NULL,
                'alt_text' => NULL,
                'category' => 'life_at_bl_teams',
                'route_slug' => 'life-at-banglalink/teams',
                'category_type' => 'teams_tab_section',
                'additional_info' => NULL,
                'is_active' => 1,
                'has_items' => 1,
                'is_default' => 0,
                'created_at' => '2020-02-17 06:06:35',
                'updated_at' => '2020-02-17 06:06:52',
                'deleted_at' => '2020-02-17 06:06:52',
            ),
            38 => 
            array (
                'id' => 45,
                'title_en' => 'Strategic Assistant Program',
                'title_bn' => 'কৌশলগত সহকারী প্রোগ্রাম',
                'slug' => 'strategic-assistant-program',
                'description_en' => NULL,
                'description_bn' => NULL,
                'image' => NULL,
                'video' => NULL,
                'alt_text' => NULL,
                'category' => 'programs_top_tab_title',
                'route_slug' => NULL,
                'category_type' => 'sap',
                'additional_info' => NULL,
                'is_active' => 1,
                'has_items' => 0,
                'is_default' => 0,
                'created_at' => '2020-02-17 07:18:25',
                'updated_at' => '2020-02-17 07:18:25',
                'deleted_at' => NULL,
            ),
            39 => 
            array (
                'id' => 46,
                'title_en' => 'Ennovators',
                'title_bn' => 'উদ্ভাবনক্ষম',
                'slug' => 'ennovators',
                'description_en' => NULL,
                'description_bn' => NULL,
                'image' => NULL,
                'video' => NULL,
                'alt_text' => NULL,
                'category' => 'programs_top_tab_title',
                'route_slug' => NULL,
                'category_type' => 'ennovators',
                'additional_info' => NULL,
                'is_active' => 1,
                'has_items' => 0,
                'is_default' => 0,
                'created_at' => '2020-02-17 07:18:25',
                'updated_at' => '2020-02-17 07:18:25',
                'deleted_at' => NULL,
            ),
            40 => 
            array (
                'id' => 47,
                'title_en' => 'Advanced Internship Program',
                'title_bn' => 'কৌশলগত সহকারী প্রোগ্রাম',
                'slug' => 'advanced-internship-program',
                'description_en' => NULL,
                'description_bn' => NULL,
                'image' => NULL,
                'video' => NULL,
                'alt_text' => NULL,
                'category' => 'programs_top_tab_title',
                'route_slug' => NULL,
                'category_type' => 'aip',
                'additional_info' => NULL,
                'is_active' => 1,
                'has_items' => 0,
                'is_default' => 0,
                'created_at' => '2020-02-17 07:18:25',
                'updated_at' => '2020-02-17 07:18:25',
                'deleted_at' => NULL,
            ),
            41 => 
            array (
                'id' => 48,
                'title_en' => 'Sap News Section',
                'title_bn' => 'Sap News Section Bangla',
                'slug' => 'sap_news_section',
                'description_en' => NULL,
                'description_bn' => NULL,
                'image' => NULL,
                'video' => NULL,
                'alt_text' => NULL,
                'category' => 'programs_progeneral',
                'route_slug' => 'programs/progeneral',
                'category_type' => 'sap',
                'additional_info' => '{"additional_type": "programs_news_section"}',
                'is_active' => 1,
                'has_items' => 1,
                'is_default' => 0,
                'created_at' => '2020-02-18 06:58:26',
                'updated_at' => '2020-02-24 09:00:26',
                'deleted_at' => NULL,
            ),
            42 => 
            array (
                'id' => 49,
                'title_en' => 'Box icon sections for SAP',
                'title_bn' => NULL,
                'slug' => 'box_icon_sections_for_sap',
                'description_en' => NULL,
                'description_bn' => NULL,
                'image' => NULL,
                'video' => NULL,
                'alt_text' => NULL,
                'category' => 'programs_proiconbox',
                'route_slug' => 'programs/proiconbox',
                'category_type' => 'sap',
                'additional_info' => NULL,
                'is_active' => 0,
                'has_items' => 1,
                'is_default' => 0,
                'created_at' => '2020-02-19 04:18:40',
                'updated_at' => '2020-02-24 08:48:23',
                'deleted_at' => NULL,
            ),
            43 => 
            array (
                'id' => 50,
                'title_en' => 'Steps',
                'title_bn' => 'Steps',
                'slug' => 'steps',
                'description_en' => NULL,
                'description_bn' => NULL,
                'image' => NULL,
                'video' => NULL,
                'alt_text' => NULL,
                'category' => 'programs_progeneral',
                'route_slug' => 'programs/progeneral',
                'category_type' => 'sap',
                'additional_info' => '{"additional_type": "programs_steps"}',
                'is_active' => 1,
                'has_items' => 1,
                'is_default' => 0,
                'created_at' => '2020-02-19 04:21:32',
                'updated_at' => '2020-02-24 09:00:32',
                'deleted_at' => NULL,
            ),
            44 => 
            array (
                'id' => 51,
                'title_en' => 'AIP News Sections',
                'title_bn' => NULL,
                'slug' => 'aip_news_sections',
                'description_en' => NULL,
                'description_bn' => NULL,
                'image' => NULL,
                'video' => NULL,
                'alt_text' => NULL,
                'category' => 'programs_progeneral',
                'route_slug' => 'programs/progeneral',
                'category_type' => 'aip',
                'additional_info' => '{"additional_type": "programs_news_section"}',
                'is_active' => 1,
                'has_items' => 1,
                'is_default' => 0,
                'created_at' => '2020-02-19 04:24:25',
                'updated_at' => '2020-02-24 09:00:38',
                'deleted_at' => NULL,
            ),
            45 => 
            array (
                'id' => 52,
                'title_en' => 'Box icon sections for AIP',
                'title_bn' => NULL,
                'slug' => 'box_icon_sections_for_aip',
                'description_en' => NULL,
                'description_bn' => NULL,
                'image' => NULL,
                'video' => NULL,
                'alt_text' => NULL,
                'category' => 'programs_proiconbox',
                'route_slug' => 'programs/proiconbox',
                'category_type' => 'aip',
                'additional_info' => NULL,
                'is_active' => 0,
                'has_items' => 1,
                'is_default' => 0,
                'created_at' => '2020-02-19 04:26:11',
                'updated_at' => '2020-02-24 08:48:29',
                'deleted_at' => NULL,
            ),
            46 => 
            array (
                'id' => 53,
                'title_en' => 'Steps',
                'title_bn' => 'Steps',
                'slug' => 'steps',
                'description_en' => NULL,
                'description_bn' => NULL,
                'image' => NULL,
                'video' => NULL,
                'alt_text' => NULL,
                'category' => 'programs_progeneral',
                'route_slug' => 'programs/progeneral',
                'category_type' => 'aip',
                'additional_info' => '{"additional_type": "programs_steps"}',
                'is_active' => 1,
                'has_items' => 1,
                'is_default' => 0,
                'created_at' => '2020-02-19 04:28:33',
                'updated_at' => '2020-02-24 09:00:45',
                'deleted_at' => NULL,
            ),
            47 => 
            array (
                'id' => 54,
                'title_en' => 'Events',
                'title_bn' => 'Events',
                'slug' => 'events',
                'description_en' => NULL,
                'description_bn' => NULL,
                'image' => NULL,
                'video' => NULL,
                'alt_text' => NULL,
                'category' => 'programs_progeneral',
                'route_slug' => 'programs/progeneral',
                'category_type' => 'aip',
                'additional_info' => '{"additional_type": "programs_events"}',
                'is_active' => 1,
                'has_items' => 1,
                'is_default' => 0,
                'created_at' => '2020-02-19 04:48:41',
                'updated_at' => '2020-02-24 09:00:51',
                'deleted_at' => NULL,
            ),
            48 => 
            array (
                'id' => 55,
                'title_en' => 'Photo Gallery',
                'title_bn' => 'Photo Gallery',
                'slug' => 'photo_gallery',
                'description_en' => NULL,
                'description_bn' => NULL,
                'image' => NULL,
                'video' => NULL,
                'alt_text' => NULL,
                'category' => 'programs_photogallery',
                'route_slug' => 'programs/photogallery',
                'category_type' => 'aip',
                'additional_info' => '{"sider_info": {"sliding_speed": "40"}}',
                'is_active' => 0,
                'has_items' => 1,
                'is_default' => 0,
                'created_at' => '2020-02-19 05:09:55',
                'updated_at' => '2020-02-24 08:42:37',
                'deleted_at' => NULL,
            ),
            49 => 
            array (
                'id' => 56,
                'title_en' => 'Ut quis doloremque',
                'title_bn' => 'Do dolor eum aut sit',
                'slug' => 'ut_quis_doloremque_',
                'description_en' => 'Incidunt praesentiu',
                'description_bn' => 'Officiis eos amet',
                'image' => 'assetlite/images/ecarrer/general_section/MfWKb0WdJbg5LP3ZZ066ItUkzjip8uIhXnS44WEv.jpeg',
                'video' => NULL,
                'alt_text' => 'Quis officiis assume',
                'category' => 'vacancy_viconbox',
                'route_slug' => 'vacancy/viconbox',
                'category_type' => NULL,
                'additional_info' => NULL,
                'is_active' => 1,
                'has_items' => 0,
                'is_default' => 0,
                'created_at' => '2020-02-19 10:00:00',
                'updated_at' => '2020-02-19 10:00:15',
                'deleted_at' => '2020-02-19 10:00:15',
            ),
            50 => 
            array (
                'id' => 57,
                'title_en' => 'Batch 2',
                'title_bn' => 'ব্যাচ 2',
                'slug' => 'batch_2',
                'description_en' => NULL,
                'description_bn' => NULL,
                'image' => NULL,
                'video' => NULL,
                'alt_text' => NULL,
                'category' => 'programs_sapbatches',
                'route_slug' => 'programs/sapbatches',
                'category_type' => 'batch_content',
                'additional_info' => NULL,
                'is_active' => 1,
                'has_items' => 1,
                'is_default' => 0,
                'created_at' => '2020-02-20 05:49:04',
                'updated_at' => '2020-02-24 09:18:43',
                'deleted_at' => '2020-02-24 09:18:43',
            ),
        ));
        
        
    }
}