<?php

use Illuminate\Database\Seeder;

class EcarrerEcarrerPortalItemsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('ecarrer_portal_items')->delete();
        
        \DB::table('ecarrer_portal_items')->insert(array (
            0 => 
            array (
                'id' => 1,
                'ecarrer_portals_id' => 1,
                'title_en' => 'title of the News changed',
                'title_bn' => 'title of the News Bangla',
            'description_en' => 'The purpose of lorem ipsum is to create a natural looking block of text (sentence, paragraph, page, etc.) that doesn\'t distract from the layout. A practice not without controversy, laying out pages with meaningless filler text can be very useful when the focus is meant to be on design, not content.',
            'description_bn' => 'লোরেম ইপসামের উদ্দেশ্য হ\'ল পাঠ্য (বাক্য, অনুচ্ছেদ, পৃষ্ঠা, ইত্যাদি) এর প্রাকৃতিক চেহারা ব্লক তৈরি করা যা বিন্যাস থেকে বিচ্যুত হয় না। কোনও বিতর্ক ছাড়াই নয়, অর্থহীন ফিলার পাঠ্য সহ পৃষ্ঠাগুলি ছড়িয়ে দেওয়া খুব অনুশীলন যখন ফোকাসটি ডিজাইনের উপর নির্ভর করে, বিষয়বস্তুতে নয়।',
                'image' => 'assetlite/images/ecarrer/general_section/0gSCQYGhKRNBYDfKgyRi2VLC5Z6jXrIR9fASmeJs.png',
                'video' => NULL,
                'alt_text' => 'Banner Image eidted',
                'alt_links' => NULL,
                'call_to_action' => NULL,
                'additional_info' => NULL,
                'is_active' => 1,
                'is_default' => 0,
                'created_at' => '2020-02-04 11:53:56',
                'updated_at' => '2020-02-20 11:34:37',
                'deleted_at' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'ecarrer_portals_id' => 1,
                'title_en' => 'title of the News',
                'title_bn' => 'title of the News  Bangla',
                'description_en' => 'To be a Pioneer; working at the frontier to unlock new opportunities for customers as they navigate the digital world.To be a Pioneer; working at the frontier to unlock new opportunities for customers.',
                'description_bn' => 'To be a Pioneer; working at the frontier to unlock new opportunities for customers as they navigate the digital world.To be a Pioneer; working at the frontier to unlock new opportunities for customers.',
                'image' => NULL,
                'video' => NULL,
                'alt_text' => 'facebook',
                'alt_links' => NULL,
                'call_to_action' => NULL,
                'additional_info' => NULL,
                'is_active' => 1,
                'is_default' => 0,
                'created_at' => '2020-02-04 11:54:29',
                'updated_at' => '2020-02-05 12:01:36',
                'deleted_at' => '2020-02-05 12:01:36',
            ),
            2 => 
            array (
                'id' => 3,
                'ecarrer_portals_id' => 1,
                'title_en' => 'title of the News',
                'title_bn' => 'title of the News',
            'description_en' => 'The purpose of lorem ipsum is to create a natural looking block of text (sentence, paragraph, page, etc.) that doesn\'t distract from the layout. A practice not without controversy, laying out pages with meaningless filler text can be very useful when the focus is meant to be on design, not content.',
            'description_bn' => 'লোরেম ইপসামের উদ্দেশ্য হ\'ল পাঠ্য (বাক্য, অনুচ্ছেদ, পৃষ্ঠা, ইত্যাদি) এর প্রাকৃতিক চেহারা ব্লক তৈরি করা যা বিন্যাস থেকে বিচ্যুত হয় না। কোনও বিতর্ক ছাড়াই নয়, অর্থহীন ফিলার পাঠ্য সহ পৃষ্ঠাগুলি ছড়িয়ে দেওয়া খুব অনুশীলন যখন ফোকাসটি ডিজাইনের উপর নির্ভর করে, বিষয়বস্তুতে নয়।',
                'image' => 'assetlite/images/ecarrer/general_section/vpbK2EyKJia9ZizVn3gS4ENl0Par5LcHLr0i2KF0.jpeg',
                'video' => NULL,
                'alt_text' => 'title of the News',
                'alt_links' => NULL,
                'call_to_action' => NULL,
                'additional_info' => NULL,
                'is_active' => 1,
                'is_default' => 0,
                'created_at' => '2020-02-05 12:01:51',
                'updated_at' => '2020-02-20 09:50:37',
                'deleted_at' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'ecarrer_portals_id' => 2,
                'title_en' => 'Ut irure provident',
                'title_bn' => 'Repellendus Assumen',
                'description_en' => 'Assumenda veritatis',
                'description_bn' => 'Cupidatat quia molli',
                'image' => NULL,
                'video' => NULL,
                'alt_text' => 'Velit culpa quasi',
                'alt_links' => NULL,
                'call_to_action' => 'a:1:{s:8:"button_1";a:3:{s:8:"label_en";s:19:"Id qui voluptate vi";s:8:"label_bn";s:20:"Ut vel dolorum aliqu";s:4:"link";s:20:"Architecto sed exerc";}}',
                'additional_info' => NULL,
                'is_active' => 0,
                'is_default' => 0,
                'created_at' => '2020-02-05 13:50:40',
                'updated_at' => '2020-02-24 08:25:06',
                'deleted_at' => '2020-02-24 08:25:06',
            ),
            4 => 
            array (
                'id' => 5,
                'ecarrer_portals_id' => 2,
                'title_en' => 'Voluptate asperiores',
                'title_bn' => 'Omnis labore id con',
                'description_en' => 'To Be A Pioneer; Working At The Frontier To Unlock New Opportunities For Customers As They Navigate The Digital World.To Be A Pioneer; Working At The Frontier To Unlock New Opportunities For Customers.',
                'description_bn' => 'Dolorem perspiciatis',
                'image' => 'assetlite/images/ecarrer/general_section/faQf3S1MOPMw5EXOEIkPpgF85hzqk1YRNnkJW4IB.jpeg',
                'video' => NULL,
                'alt_text' => 'Hic molestias possim',
                'alt_links' => NULL,
                'call_to_action' => 'a:1:{s:8:"button_1";a:3:{s:8:"label_en";s:20:"Vel deleniti ullam s";s:8:"label_bn";s:20:"Quibusdam alias magn";s:4:"link";s:19:"Do elit est nostrum";}}',
                'additional_info' => NULL,
                'is_active' => 1,
                'is_default' => 0,
                'created_at' => '2020-02-05 14:03:03',
                'updated_at' => '2020-02-24 08:25:06',
                'deleted_at' => '2020-02-24 08:25:06',
            ),
            5 => 
            array (
                'id' => 6,
                'ecarrer_portals_id' => 12,
                'title_en' => 'facebook',
                'title_bn' => NULL,
                'description_en' => NULL,
                'description_bn' => NULL,
                'image' => 'assetlite/images/ecarrer/general_section/KcS6Lo4cCfN9UJRfCIIQqxIa5QgAJ4qdC1ftGzYV.png',
                'video' => NULL,
                'alt_text' => 'facebook',
                'alt_links' => 'https://www.facebook.com',
                'call_to_action' => NULL,
                'additional_info' => NULL,
                'is_active' => 1,
                'is_default' => 0,
                'created_at' => '2020-02-05 14:41:00',
                'updated_at' => '2020-02-06 07:17:44',
                'deleted_at' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'ecarrer_portals_id' => 14,
                'title_en' => 'Arik Aas',
                'title_bn' => 'Arik Aas bangla',
                'description_en' => 'Banglalink provide the fastest internet throughout the country, I never get the best experience except using Banlalink. It’s awesome service ever, I’ll always use Banglalink. Bangla',
                'description_bn' => 'বাংলালিংক সারা দেশে দ্রুততম ইন্টারনেট সরবরাহ করে, আমি কখনও বনলিংক ব্যবহার ব্যতীত সেরা অভিজ্ঞতা পাই না। এটি সর্বদা দুর্দান্ত পরিষেবা, আমি সর্বদা বাংলালিংক ব্যবহার করব। বাংলা',
                'image' => 'assetlite/images/ecarrer/general_section/zVPiuNyjFal4hGWMsvZltZxx2lHCJmiKICh90Mm3.jpeg',
                'video' => NULL,
                'alt_text' => 'asdasdsa',
                'alt_links' => NULL,
                'call_to_action' => NULL,
                'additional_info' => '{"testimonial_info": {"university_bn": "University bangla", "university_en": "University English"}}',
                'is_active' => 1,
                'is_default' => 0,
                'created_at' => '2020-02-06 05:22:11',
                'updated_at' => '2020-02-24 09:16:53',
                'deleted_at' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'ecarrer_portals_id' => 12,
                'title_en' => 'Twitter',
                'title_bn' => NULL,
                'description_en' => NULL,
                'description_bn' => NULL,
                'image' => 'assetlite/images/ecarrer/general_section/D2L2VegKdzm1Ntd3eSR7V82SHMdER3ArDFDIWMQX.png',
                'video' => NULL,
                'alt_text' => 'Twitter',
                'alt_links' => 'www.twitter.com',
                'call_to_action' => NULL,
                'additional_info' => NULL,
                'is_active' => 1,
                'is_default' => 0,
                'created_at' => '2020-02-06 07:18:23',
                'updated_at' => '2020-02-06 07:18:23',
                'deleted_at' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'ecarrer_portals_id' => 18,
                'title_en' => 'Tab title',
                'title_bn' => 'Tab title bangla',
                'description_en' => 'To Be A Pioneer; Working At The Frontier To Unlock New Opportunities For Customers As They Navigate The Digital World.To Be A Pioneer; Working At The Frontier To Unlock New Opportunities For Customers.',
                'description_bn' => 'To Be A Pioneer; Working At The Frontier To Unlock New Opportunities For Customers As They Navigate The Digital World.To Be A Pioneer; Working At The Frontier To Unlock New Opportunities For Customers.',
                'image' => 'assetlite/images/ecarrer/general_section/kIGxKG86k6nojJ3ZRQ2c87OFI9aStSsmwCrhqfwb.jpeg',
                'video' => NULL,
                'alt_text' => 'Alter text',
                'alt_links' => NULL,
                'call_to_action' => 'a:2:{s:8:"button_1";a:3:{s:8:"label_en";s:28:"See all commercial job offer";s:8:"label_bn";s:28:"See all commercial job offer";s:4:"link";s:1:"#";}s:8:"button_2";a:3:{s:8:"label_en";s:4:"test";s:8:"label_bn";s:4:"test";s:4:"link";s:1:"#";}}',
                'additional_info' => NULL,
                'is_active' => 1,
                'is_default' => 0,
                'created_at' => '2020-02-06 07:22:47',
                'updated_at' => '2020-02-24 08:25:08',
                'deleted_at' => '2020-02-24 08:25:08',
            ),
            9 => 
            array (
                'id' => 10,
                'ecarrer_portals_id' => 20,
                'title_en' => 'Title Of The News 02',
                'title_bn' => NULL,
                'description_en' => 'To Be A Pioneer; Working At The Frontier To Unlock New Opportunities For Customers As They Navigate The Digital World.To Be A Pioneer; Working At The Frontier To Unlock New Opportunities For Customers.',
                'description_bn' => 'To Be A Pioneer; Working At The Frontier To Unlock New Opportunities For Customers As They Navigate The Digital World.To Be A Pioneer; Working At The Frontier To Unlock New Opportunities For Customers.',
                'image' => 'assetlite/images/ecarrer/general_section/WIMp1VxMiEZJAgJF3HEBKgIFl2jlhLeUo2aGx2rK.jpeg',
                'video' => NULL,
                'alt_text' => 'Alter text',
                'alt_links' => NULL,
                'call_to_action' => 'a:2:{s:8:"button_1";a:3:{s:8:"label_en";s:9:"Apply Now";s:8:"label_bn";s:6:"Bangla";s:4:"link";s:1:"#";}s:8:"button_2";a:3:{s:8:"label_en";s:3:"FAQ";s:8:"label_bn";s:10:"FAQ Bangla";s:4:"link";s:1:"#";}}',
                'additional_info' => NULL,
                'is_active' => 1,
                'is_default' => 0,
                'created_at' => '2020-02-06 07:37:27',
                'updated_at' => '2020-02-16 04:46:48',
                'deleted_at' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'ecarrer_portals_id' => 9,
                'title_en' => 'slide 1',
                'title_bn' => NULL,
                'description_en' => NULL,
                'description_bn' => NULL,
                'image' => 'assetlite/images/ecarrer/general_section/Bds8DqZBXv9VozfE4OvJzXKivQxxTA5rh7X6wqhB.jpeg',
                'video' => NULL,
                'alt_text' => 'Banner Image',
                'alt_links' => NULL,
                'call_to_action' => NULL,
                'additional_info' => NULL,
                'is_active' => 1,
                'is_default' => 0,
                'created_at' => '2020-02-06 07:39:11',
                'updated_at' => '2020-02-06 07:39:11',
                'deleted_at' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'ecarrer_portals_id' => 9,
                'title_en' => 'slide 2',
                'title_bn' => NULL,
                'description_en' => NULL,
                'description_bn' => NULL,
                'image' => 'assetlite/images/ecarrer/general_section/WvXMoT1jDCvtp9Lb9lY2635doSZ1a87HATzwvPPp.jpeg',
                'video' => NULL,
                'alt_text' => 'Banner Image',
                'alt_links' => NULL,
                'call_to_action' => NULL,
                'additional_info' => NULL,
                'is_active' => 1,
                'is_default' => 0,
                'created_at' => '2020-02-06 07:39:29',
                'updated_at' => '2020-02-06 07:39:29',
                'deleted_at' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'ecarrer_portals_id' => 13,
                'title_en' => 'facebook',
                'title_bn' => NULL,
                'description_en' => NULL,
                'description_bn' => NULL,
                'image' => 'assetlite/images/ecarrer/general_section/Z18glVtag7M881ZENSzTqUaqignrvyEXGcLV2TI0.png',
                'video' => NULL,
                'alt_text' => 'facebook',
                'alt_links' => 'http://codeboomers.ml/bl/demo/dist/images/socials/fb.png',
                'call_to_action' => NULL,
                'additional_info' => NULL,
                'is_active' => 1,
                'is_default' => 0,
                'created_at' => '2020-02-06 07:45:40',
                'updated_at' => '2020-02-06 07:45:40',
                'deleted_at' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'ecarrer_portals_id' => 13,
                'title_en' => 'Twitter',
                'title_bn' => NULL,
                'description_en' => NULL,
                'description_bn' => NULL,
                'image' => 'assetlite/images/ecarrer/general_section/B91xdPyzWST8fjppuopmhwayR85QwsWDMd3YVpzZ.png',
                'video' => NULL,
                'alt_text' => 'Twitter',
                'alt_links' => 'amar-offers',
                'call_to_action' => NULL,
                'additional_info' => NULL,
                'is_active' => 1,
                'is_default' => 0,
                'created_at' => '2020-02-06 07:46:09',
                'updated_at' => '2020-02-17 10:38:02',
                'deleted_at' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'ecarrer_portals_id' => 21,
                'title_en' => 'Strategic Assistant Program',
                'title_bn' => 'কৌশলগত সহকারী প্রোগ্রাম বাংলা',
                'description_en' => 'Banglalink, in collaboration with the Bangladesh High-Tech Park Authority',
                'description_bn' => 'বাংলালিংক, বাংলাদেশ হাই-টেক পার্ক কর্তৃপক্ষের সহযোগিতায়',
                'image' => 'assetlite/images/ecarrer/general_section/7CRlwKuUJaD4DTz3QpoPZ4fcDJ7VpFtYPUvFTPTv.jpeg',
                'video' => NULL,
                'alt_text' => 'Banner Image',
                'alt_links' => NULL,
                'call_to_action' => NULL,
                'additional_info' => NULL,
                'is_active' => 1,
                'is_default' => 0,
                'created_at' => '2020-02-06 10:06:42',
                'updated_at' => '2020-02-24 08:29:49',
                'deleted_at' => '2020-02-24 08:29:49',
            ),
            15 => 
            array (
                'id' => 16,
                'ecarrer_portals_id' => 22,
                'title_en' => 'slide 1',
                'title_bn' => NULL,
                'description_en' => NULL,
                'description_bn' => NULL,
                'image' => 'assetlite/images/ecarrer/general_section/tVqRCy5wCPLOvyaIH3Br1PRDzizHnda6zDY8u2oJ.jpeg',
                'video' => NULL,
                'alt_text' => 'Alter text',
                'alt_links' => NULL,
                'call_to_action' => NULL,
                'additional_info' => NULL,
                'is_active' => 1,
                'is_default' => 0,
                'created_at' => '2020-02-06 10:08:46',
                'updated_at' => '2020-02-17 14:03:29',
                'deleted_at' => NULL,
            ),
            16 => 
            array (
                'id' => 17,
                'ecarrer_portals_id' => 23,
                'title_en' => 'Erik Aas',
                'title_bn' => NULL,
                'description_en' => 'Banglalink provide the fastest internet throughout the country, I never get the best experience except using Banlalink. It’s awesome service ever, I’ll always use Banglalink.',
                'description_bn' => 'Banglalink provide the fastest internet throughout the country, I never get the best experience except using Banlalink. It’s awesome service ever, I’ll always use Banglalink.',
                'image' => 'assetlite/images/ecarrer/general_section/bARTHmMwL3smFfgPxB3Bw8UN0Kx0BZ4xfDNDwKU6.jpeg',
                'video' => NULL,
                'alt_text' => 'image',
                'alt_links' => NULL,
                'call_to_action' => NULL,
                'additional_info' => '{"testimonial_info": {"university_bn": "University bangla", "university_en": "University"}}',
                'is_active' => 1,
                'is_default' => 0,
                'created_at' => '2020-02-06 10:16:36',
                'updated_at' => '2020-02-13 13:11:06',
                'deleted_at' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'ecarrer_portals_id' => 14,
                'title_en' => 'Erik Aas',
                'title_bn' => NULL,
                'description_en' => 'Banglalink provide the fastest internet throughout the country, I never get the best experience except using Banlalink. It’s awesome service ever, I’ll always use Banglalink. Bangla',
                'description_bn' => 'বাংলালিংক সারা দেশে দ্রুততম ইন্টারনেট সরবরাহ করে, আমি কখনও বনলিংক ব্যবহার ব্যতীত সেরা অভিজ্ঞতা পাই না। এটি সর্বদা দুর্দান্ত পরিষেবা, আমি সর্বদা বাংলালিংক ব্যবহার করব। বাংলা',
                'image' => 'assetlite/images/ecarrer/general_section/EjorzP8g2nfEPf0LdzmiZ9CDwslNyWF2OTUomiJN.jpeg',
                'video' => NULL,
                'alt_text' => 'Banner Image',
                'alt_links' => NULL,
                'call_to_action' => NULL,
                'additional_info' => '{"testimonial_info": {"university_bn": "University bangla", "university_en": "University"}}',
                'is_active' => 1,
                'is_default' => 0,
                'created_at' => '2020-02-06 10:27:43',
                'updated_at' => '2020-02-24 09:16:40',
                'deleted_at' => NULL,
            ),
            18 => 
            array (
                'id' => 19,
                'ecarrer_portals_id' => 6,
                'title_en' => 'title of the News 04',
                'title_bn' => 'title of the News 04 bangla',
                'description_en' => 'To be a Pioneer; working at the frontier to unlock new opportunities for customers as they navigate the digital world.To be a Pioneer; working at the frontier to unlock new opportunities for customers. NEW',
                'description_bn' => 'পাইওনিয়ার হতে; ডিজিটাল ওয়ার্ল্ড নেভিগেট করার সাথে সাথে গ্রাহকদের জন্য নতুন সুযোগগুলি আনলক করতে সীমান্তে কাজ করা Tপিয়িনিয়ার হতে হবে; গ্রাহকদের জন্য নতুন সুযোগ আনলক সীমান্তে কাজ।',
                'image' => 'assetlite/images/ecarrer/general_section/nETVRtiseXMUNPMXv9OXKibZhLDj77gY8qJF7KQQ.png',
                'video' => NULL,
                'alt_text' => 'Banner Image',
                'alt_links' => NULL,
                'call_to_action' => NULL,
                'additional_info' => NULL,
                'is_active' => 1,
                'is_default' => 0,
                'created_at' => '2020-02-11 09:05:29',
                'updated_at' => '2020-02-17 09:31:07',
                'deleted_at' => NULL,
            ),
            19 => 
            array (
                'id' => 20,
                'ecarrer_portals_id' => 6,
                'title_en' => 'title of the News 01',
                'title_bn' => 'title of the News 02 Bangla',
                'description_en' => 'To be a Pioneer; working at the frontier to unlock new opportunities for customers as they navigate the digital world.To be a Pioneer; working at the frontier to unlock new opportunities for customers.',
                'description_bn' => 'To be a Pioneer; working at the frontier to unlock new opportunities for customers as they navigate the digital world.To be a Pioneer; working at the frontier to unlock new opportunities for customers.',
                'image' => 'assetlite/images/ecarrer/general_section/uPBOwXKTDuc2OfbEeCTASCxn1YcMr2Pz8hRiK0rg.png',
                'video' => NULL,
                'alt_text' => 'Vlues',
                'alt_links' => NULL,
                'call_to_action' => NULL,
                'additional_info' => NULL,
                'is_active' => 1,
                'is_default' => 0,
                'created_at' => '2020-02-11 09:05:56',
                'updated_at' => '2020-02-17 09:23:59',
                'deleted_at' => NULL,
            ),
            20 => 
            array (
                'id' => 21,
                'ecarrer_portals_id' => 7,
                'title_en' => 'Title Of The News 03',
                'title_bn' => 'Title of the news 03',
                'description_en' => 'To be a Pioneer; working at the frontier to unlock new opportunities for customers as they navigate the digital world.To be a Pioneer; working at the frontier to unlock new opportunities for customers.',
                'description_bn' => 'To be a Pioneer; working at the frontier to unlock new opportunities for customers as they navigate the digital world.To be a Pioneer; working at the frontier to unlock new opportunities for customers.',
                'image' => 'assetlite/images/ecarrer/general_section/9R45qqVjRSv0cDiiExOLs4SMaThixBtuy1ETCT7L.png',
                'video' => NULL,
                'alt_text' => 'we at camplus',
                'alt_links' => NULL,
                'call_to_action' => NULL,
                'additional_info' => NULL,
                'is_active' => 1,
                'is_default' => 0,
                'created_at' => '2020-02-11 09:07:36',
                'updated_at' => '2020-02-11 09:08:55',
                'deleted_at' => NULL,
            ),
            21 => 
            array (
                'id' => 22,
                'ecarrer_portals_id' => 7,
                'title_en' => 'Title Of The News 02',
                'title_bn' => 'title of the News 02 Bangla',
                'description_en' => 'To be a Pioneer; working at the frontier to unlock new opportunities for customers as they navigate the digital world.To be a Pioneer; working at the frontier to unlock new opportunities for customers. NEW',
                'description_bn' => 'পাইওনিয়ার হতে; ডিজিটাল ওয়ার্ল্ড নেভিগেট করার সাথে সাথে গ্রাহকদের জন্য নতুন সুযোগগুলি আনলক করতে সীমান্তে কাজ করা Tপিয়িনিয়ার হতে হবে; গ্রাহকদের জন্য নতুন সুযোগ আনলক সীমান্তে কাজ।',
                'image' => 'assetlite/images/ecarrer/general_section/EXa8pzKYhEXOsAgVbWDVo5tfU9L9k3fRUSajcFKN.jpeg',
                'video' => NULL,
                'alt_text' => 'Alter text',
                'alt_links' => NULL,
                'call_to_action' => NULL,
                'additional_info' => NULL,
                'is_active' => 1,
                'is_default' => 0,
                'created_at' => '2020-02-11 09:08:02',
                'updated_at' => '2020-02-17 09:54:09',
                'deleted_at' => NULL,
            ),
            22 => 
            array (
                'id' => 23,
                'ecarrer_portals_id' => 22,
                'title_en' => 'slide 2',
                'title_bn' => NULL,
                'description_en' => NULL,
                'description_bn' => NULL,
                'image' => 'assetlite/images/ecarrer/general_section/JrRqxF4PYdz0F8fs63CaHYHIVHxyoaCVLDw9guOf.jpeg',
                'video' => NULL,
                'alt_text' => 'Alter text',
                'alt_links' => NULL,
                'call_to_action' => NULL,
                'additional_info' => NULL,
                'is_active' => 1,
                'is_default' => 0,
                'created_at' => '2020-02-11 10:15:48',
                'updated_at' => '2020-02-17 07:43:48',
                'deleted_at' => NULL,
            ),
            23 => 
            array (
                'id' => 24,
                'ecarrer_portals_id' => 22,
                'title_en' => 'slide 3',
                'title_bn' => NULL,
                'description_en' => NULL,
                'description_bn' => NULL,
                'image' => 'assetlite/images/ecarrer/general_section/lbhH5Bp3zFE6Nm7Lj02gSP1iDvlBLvHci1RyTIfA.jpeg',
                'video' => NULL,
                'alt_text' => 'slide 3',
                'alt_links' => NULL,
                'call_to_action' => NULL,
                'additional_info' => NULL,
                'is_active' => 1,
                'is_default' => 0,
                'created_at' => '2020-02-11 10:16:49',
                'updated_at' => '2020-02-17 08:11:50',
                'deleted_at' => '2020-02-17 08:11:50',
            ),
            24 => 
            array (
                'id' => 25,
                'ecarrer_portals_id' => 22,
                'title_en' => 'slide 4',
                'title_bn' => NULL,
                'description_en' => NULL,
                'description_bn' => NULL,
                'image' => 'assetlite/images/ecarrer/general_section/Rz7eNOo5kVkdXKQGDk5EO58sZsxYbHAt0r6cwyn5.jpeg',
                'video' => NULL,
                'alt_text' => 'slide 4',
                'alt_links' => NULL,
                'call_to_action' => NULL,
                'additional_info' => NULL,
                'is_active' => 1,
                'is_default' => 0,
                'created_at' => '2020-02-11 10:16:59',
                'updated_at' => '2020-02-17 08:07:00',
                'deleted_at' => NULL,
            ),
            25 => 
            array (
                'id' => 26,
                'ecarrer_portals_id' => 22,
                'title_en' => 'slide 5',
                'title_bn' => NULL,
                'description_en' => NULL,
                'description_bn' => NULL,
                'image' => 'assetlite/images/ecarrer/general_section/z3DrEkl3hG8R9MctSenjIkB2bPxXFGHY0G9wSnN7.jpeg',
                'video' => NULL,
                'alt_text' => 'slide 5',
                'alt_links' => NULL,
                'call_to_action' => NULL,
                'additional_info' => NULL,
                'is_active' => 1,
                'is_default' => 0,
                'created_at' => '2020-02-11 10:17:18',
                'updated_at' => '2020-02-17 08:08:05',
                'deleted_at' => NULL,
            ),
            26 => 
            array (
                'id' => 27,
                'ecarrer_portals_id' => 22,
                'title_en' => 'slide 6',
                'title_bn' => NULL,
                'description_en' => NULL,
                'description_bn' => NULL,
                'image' => 'assetlite/images/ecarrer/general_section/qPanZwMuAw6sC3kKqyeEgURPPrP1VehmYtTdToo9.jpeg',
                'video' => NULL,
                'alt_text' => 'slide 6',
                'alt_links' => NULL,
                'call_to_action' => NULL,
                'additional_info' => NULL,
                'is_active' => 0,
                'is_default' => 0,
                'created_at' => '2020-02-11 10:17:29',
                'updated_at' => '2020-02-17 07:47:45',
                'deleted_at' => NULL,
            ),
            27 => 
            array (
                'id' => 28,
                'ecarrer_portals_id' => 21,
                'title_en' => 'Advance Internship Program',
                'title_bn' => 'Advance Internship Program Bangla',
                'description_en' => 'Banglalink, In Collaboration With Bangladesh Hi-Tech Park Authority',
                'description_bn' => 'Banglalink, In Collaboration With Bangladesh Hi-Tech Park Authority Bangla',
                'image' => 'assetlite/images/ecarrer/general_section/DB43q7wciztDJQU6zGI5RLcv9byKLqF2AoCCLEiQ.jpeg',
                'video' => NULL,
                'alt_text' => 'Advance Internship Program alt text',
                'alt_links' => NULL,
                'call_to_action' => NULL,
                'additional_info' => NULL,
                'is_active' => 1,
                'is_default' => 0,
                'created_at' => '2020-02-11 11:16:55',
                'updated_at' => '2020-02-24 08:29:49',
                'deleted_at' => '2020-02-24 08:29:49',
            ),
            28 => 
            array (
                'id' => 29,
                'ecarrer_portals_id' => 6,
                'title_en' => 'title of the News 02',
                'title_bn' => 'title of the News 02 bangla',
                'description_en' => 'To be a Pioneer; working at the frontier to unlock new opportunities for customers as they navigate the digital world.To be a Pioneer; working at the frontier to unlock new opportunities for customers.',
                'description_bn' => 'To be a Pioneer; working at the frontier to unlock new opportunities for customers as they navigate the digital world.To be a Pioneer; working at the frontier to unlock new opportunities for customers bangla.',
                'image' => 'assetlite/images/ecarrer/general_section/CkCbWuKJDCMsflxvsMDpayiZlzPFoP8Pl8TG0ttp.png',
                'video' => NULL,
                'alt_text' => 'title of the News 02 alt',
                'alt_links' => NULL,
                'call_to_action' => NULL,
                'additional_info' => NULL,
                'is_active' => 1,
                'is_default' => 0,
                'created_at' => '2020-02-11 14:04:21',
                'updated_at' => '2020-02-17 09:24:04',
                'deleted_at' => NULL,
            ),
            29 => 
            array (
                'id' => 30,
                'ecarrer_portals_id' => 6,
                'title_en' => 'title of the News 05',
                'title_bn' => 'title of the News 05',
                'description_en' => 'To be a Pioneer; working at the frontier to unlock new opportunities for customers as they navigate the digital world.To be a Pioneer; working at the frontier to unlock new opportunities for customers.',
                'description_bn' => 'To be a Pioneer; working at the frontier to unlock new opportunities for customers as they navigate the digital world.To be a Pioneer; working at the frontier to unlock new opportunities for customers bangla.',
                'image' => 'assetlite/images/ecarrer/general_section/OQNZb85elNPk0bzvnVd73TG4YgbadXerZ4cUNwy7.png',
                'video' => NULL,
                'alt_text' => 'title of the News 05',
                'alt_links' => NULL,
                'call_to_action' => NULL,
                'additional_info' => NULL,
                'is_active' => 1,
                'is_default' => 0,
                'created_at' => '2020-02-11 14:07:32',
                'updated_at' => '2020-02-17 09:24:08',
                'deleted_at' => NULL,
            ),
            30 => 
            array (
                'id' => 31,
                'ecarrer_portals_id' => 6,
                'title_en' => 'title of the News 06',
                'title_bn' => 'title of the News 06',
                'description_en' => '06 To be a Pioneer; working at the frontier to unlock new opportunities for customers as they navigate the digital world.To be a Pioneer; working at the frontier to unlock new opportunities for customers.',
                'description_bn' => '06 To be a Pioneer; working at the frontier to unlock new opportunities for customers as they navigate the digital world.To be a Pioneer; working at the frontier to unlock new opportunities for customers bangla.',
                'image' => 'assetlite/images/ecarrer/general_section/LoJXWGwtxpgxIeyUYgz2fP0iouTKpE7w08KtcrqC.png',
                'video' => NULL,
                'alt_text' => 'title of the News 06',
                'alt_links' => NULL,
                'call_to_action' => NULL,
                'additional_info' => NULL,
                'is_active' => 1,
                'is_default' => 0,
                'created_at' => '2020-02-11 14:08:13',
                'updated_at' => '2020-02-17 09:23:50',
                'deleted_at' => NULL,
            ),
            31 => 
            array (
                'id' => 32,
                'ecarrer_portals_id' => 24,
                'title_en' => 'Title Goes Here',
                'title_bn' => 'Title Goes Here Bangla',
                'description_en' => 'Any Alarm Information Is Transmitted In The Form Of MMS, SMS, Calls, E-Mails Or An Alarm Receiving Center. Any Alarm Information Is Transmitted In The Form Of MMS, SMS, Calls, E-Mails Or An Alarm Receiving Center.',
                'description_bn' => 'Any Alarm Information Is Transmitted In The Form Of MMS, SMS, Calls, E-Mails Or An Alarm Receiving Center. Any Alarm Information Is Transmitted In The Form Of MMS, SMS, Calls, E-Mails Or An Alarm Receiving Center.',
                'image' => 'assetlite/images/ecarrer/general_section/vTH7ARhlZWAKa872KBwTxDy70bYINkQSjOpEKr7q.png',
                'video' => NULL,
                'alt_text' => 'Alter text',
                'alt_links' => NULL,
                'call_to_action' => NULL,
                'additional_info' => NULL,
                'is_active' => 1,
                'is_default' => 0,
                'created_at' => '2020-02-13 12:25:28',
                'updated_at' => '2020-02-13 12:25:28',
                'deleted_at' => NULL,
            ),
            32 => 
            array (
                'id' => 33,
                'ecarrer_portals_id' => 24,
                'title_en' => 'Title Goes Here',
                'title_bn' => 'Title Goes Here Bangla',
                'description_en' => 'Any Alarm Information Is Transmitted In The Form Of MMS, SMS, Calls, E-Mails Or An Alarm Receiving Center. Any Alarm Information Is Transmitted In The Form Of MMS, SMS, Calls, E-Mails Or An Alarm Receiving Center.',
                'description_bn' => 'Any Alarm Information Is Transmitted In The Form Of MMS, SMS, Calls, E-Mails Or An Alarm Receiving Center. Any Alarm Information Is Transmitted In The Form Of MMS, SMS, Calls, E-Mails Or An Alarm Receiving Center.',
                'image' => 'assetlite/images/ecarrer/general_section/NHD2G4QcS8bahqo68Yc6lsIJBUndQaqFr79Gz1I7.png',
                'video' => NULL,
                'alt_text' => 'Alter text',
                'alt_links' => NULL,
                'call_to_action' => NULL,
                'additional_info' => NULL,
                'is_active' => 1,
                'is_default' => 0,
                'created_at' => '2020-02-13 12:25:50',
                'updated_at' => '2020-02-13 12:25:50',
                'deleted_at' => NULL,
            ),
            33 => 
            array (
                'id' => 34,
                'ecarrer_portals_id' => 34,
                'title_en' => 'Image 1',
                'title_bn' => 'Imgae 1 bangla',
                'description_en' => NULL,
                'description_bn' => NULL,
                'image' => 'assetlite/images/ecarrer/general_section/OpgqbtDP8X2I8IxDDdRX1bieokkTterWyVj4smNW.png',
                'video' => NULL,
                'alt_text' => 'Alter text',
                'alt_links' => NULL,
                'call_to_action' => NULL,
                'additional_info' => NULL,
                'is_active' => 1,
                'is_default' => 0,
                'created_at' => '2020-02-13 12:32:44',
                'updated_at' => '2020-02-24 09:07:04',
                'deleted_at' => NULL,
            ),
            34 => 
            array (
                'id' => 35,
                'ecarrer_portals_id' => 34,
                'title_en' => 'Imgae 2',
                'title_bn' => NULL,
                'description_en' => NULL,
                'description_bn' => NULL,
                'image' => 'assetlite/images/ecarrer/general_section/48xiVk7fryY7t6LSwIJNAOnrtFTCQGgVyziMXvm0.png',
                'video' => NULL,
                'alt_text' => 'Alter text',
                'alt_links' => NULL,
                'call_to_action' => NULL,
                'additional_info' => NULL,
                'is_active' => 1,
                'is_default' => 0,
                'created_at' => '2020-02-13 12:33:40',
                'updated_at' => '2020-02-13 12:33:40',
                'deleted_at' => NULL,
            ),
            35 => 
            array (
                'id' => 36,
                'ecarrer_portals_id' => 36,
                'title_en' => 'Erik Aas',
                'title_bn' => NULL,
                'description_en' => 'Any Alarm Information Is Transmitted In The Form Of MMS, SMS, Calls, E-Mails Or An Alarm Receiving Center. Any Alarm Information Is Transmitted In The Form Of MMS, SMS, Calls, E-Mails Or An Alarm Receiving Center.',
                'description_bn' => 'Any Alarm Information Is Transmitted In The Form Of MMS, SMS, Calls, E-Mails Or An Alarm Receiving Center. Any Alarm Information Is Transmitted In The Form Of MMS, SMS, Calls, E-Mails Or An Alarm Receiving Center.',
                'image' => 'assetlite/images/ecarrer/general_section/2pnxBJ6Rbr7MH6uph39U1fHmmTECrXdX8TTs63QS.jpeg',
                'video' => NULL,
                'alt_text' => 'Alter text',
                'alt_links' => NULL,
                'call_to_action' => NULL,
                'additional_info' => '{"testimonial_info": {"university_bn": "University bangla", "university_en": "University"}}',
                'is_active' => 1,
                'is_default' => 0,
                'created_at' => '2020-02-13 12:40:27',
                'updated_at' => '2020-02-13 12:40:27',
                'deleted_at' => NULL,
            ),
            36 => 
            array (
                'id' => 37,
                'ecarrer_portals_id' => 36,
                'title_en' => 'Erik Aas 2',
                'title_bn' => NULL,
                'description_en' => 'Any Alarm Information Is Transmitted In The Form Of MMS, SMS, Calls, E-Mails Or An Alarm Receiving Center. Any Alarm Information Is Transmitted In The Form Of MMS, SMS, Calls, E-Mails Or An Alarm Receiving Center.',
                'description_bn' => 'Any Alarm Information Is Transmitted In The Form Of MMS, SMS, Calls, E-Mails Or An Alarm Receiving Center. Any Alarm Information Is Transmitted In The Form Of MMS, SMS, Calls, E-Mails Or An Alarm Receiving Center.',
                'image' => 'assetlite/images/ecarrer/general_section/BbSccHTfhMRz45ODrCXrtpSZxOvIXkhyfYlzQq4c.jpeg',
                'video' => NULL,
                'alt_text' => 'Alter text',
                'alt_links' => NULL,
                'call_to_action' => NULL,
                'additional_info' => '{"testimonial_info": {"university_bn": "University bangla", "university_en": "University"}}',
                'is_active' => 1,
                'is_default' => 0,
                'created_at' => '2020-02-13 12:40:56',
                'updated_at' => '2020-02-13 12:40:56',
                'deleted_at' => NULL,
            ),
            37 => 
            array (
                'id' => 38,
                'ecarrer_portals_id' => 37,
                'title_en' => 'Erik Aas',
                'title_bn' => NULL,
                'description_en' => 'Any Alarm Information Is Transmitted In The Form Of MMS, SMS, Calls, E-Mails Or An Alarm Receiving Center. Any Alarm Information Is Transmitted In The Form Of MMS, SMS, Calls, E-Mails Or An Alarm Receiving Center.',
                'description_bn' => 'Any Alarm Information Is Transmitted In The Form Of MMS, SMS, Calls, E-Mails Or An Alarm Receiving Center. Any Alarm Information Is Transmitted In The Form Of MMS, SMS, Calls, E-Mails Or An Alarm Receiving Center.',
                'image' => 'assetlite/images/ecarrer/general_section/2QjYtrfw5kUmjrZggpTUTQ2qOzLB5h2UnTk88hWb.jpeg',
                'video' => NULL,
                'alt_text' => 'Alter text',
                'alt_links' => NULL,
                'call_to_action' => NULL,
                'additional_info' => '{"testimonial_info": {"university_bn": "University bangla", "university_en": "University"}}',
                'is_active' => 1,
                'is_default' => 0,
                'created_at' => '2020-02-13 12:41:45',
                'updated_at' => '2020-02-13 12:41:45',
                'deleted_at' => NULL,
            ),
            38 => 
            array (
                'id' => 39,
                'ecarrer_portals_id' => 38,
                'title_en' => 'Event title for ennovators',
                'title_bn' => 'Event title for ennovators',
                'description_en' => 'Event title for ennovators',
                'description_bn' => 'Event title for ennovators',
                'image' => 'assetlite/images/ecarrer/general_section/LYd2ZDoKNObtZ2k8ufH1kWA7VXm7qU6UsFylfuCm.jpeg',
                'video' => NULL,
                'alt_text' => 'Alter text',
                'alt_links' => NULL,
                'call_to_action' => NULL,
                'additional_info' => NULL,
                'is_active' => 1,
                'is_default' => 0,
                'created_at' => '2020-02-13 12:43:37',
                'updated_at' => '2020-02-13 12:43:37',
                'deleted_at' => NULL,
            ),
            39 => 
            array (
                'id' => 40,
                'ecarrer_portals_id' => 38,
                'title_en' => 'Extra internet for all Banglalink users 2',
                'title_bn' => NULL,
                'description_en' => 'Event title for ennovators',
                'description_bn' => 'Any Alarm Information Is Transmitted In The Form Of MMS, SMS, Calls, E-Mails Or An Alarm Receiving Center. Any Alarm Information Is Transmitted In The Form Of MMS, SMS, Calls, E-Mails Or An Alarm Receiving Center.',
                'image' => 'assetlite/images/ecarrer/general_section/tUpiWsFJS4mV7NLPYNucIv1twPvCmaM8BwK9OPpW.jpeg',
                'video' => NULL,
                'alt_text' => 'Alter text',
                'alt_links' => NULL,
                'call_to_action' => NULL,
                'additional_info' => NULL,
                'is_active' => 1,
                'is_default' => 0,
                'created_at' => '2020-02-13 12:44:00',
                'updated_at' => '2020-02-13 12:44:00',
                'deleted_at' => NULL,
            ),
            40 => 
            array (
                'id' => 41,
                'ecarrer_portals_id' => 39,
                'title_en' => 'slider 1',
                'title_bn' => 'slider 1',
                'description_en' => NULL,
                'description_bn' => NULL,
                'image' => 'assetlite/images/ecarrer/general_section/e6BPSQ4ew7SjKqKVCQPWYZTtyr9s4efcknM08bWH.jpeg',
                'video' => NULL,
                'alt_text' => 'Banner Image',
                'alt_links' => NULL,
                'call_to_action' => NULL,
                'additional_info' => NULL,
                'is_active' => 1,
                'is_default' => 0,
                'created_at' => '2020-02-13 12:47:32',
                'updated_at' => '2020-02-13 12:47:32',
                'deleted_at' => NULL,
            ),
            41 => 
            array (
                'id' => 42,
                'ecarrer_portals_id' => 39,
                'title_en' => 'slider 1',
                'title_bn' => NULL,
                'description_en' => NULL,
                'description_bn' => NULL,
                'image' => 'assetlite/images/ecarrer/general_section/K6l5drn6jIFJpTw9tVuRMe60ZN75ohFNinJF1xg7.jpeg',
                'video' => NULL,
                'alt_text' => 'Alter text',
                'alt_links' => NULL,
                'call_to_action' => NULL,
                'additional_info' => NULL,
                'is_active' => 1,
                'is_default' => 0,
                'created_at' => '2020-02-13 12:47:58',
                'updated_at' => '2020-02-13 12:47:58',
                'deleted_at' => NULL,
            ),
            42 => 
            array (
                'id' => 43,
                'ecarrer_portals_id' => 23,
                'title_en' => 'Erik Aas 2',
                'title_bn' => NULL,
                'description_en' => 'Any Alarm Information Is Transmitted In The Form Of MMS, SMS, Calls, E-Mails Or An Alarm Receiving Center. Any Alarm Information Is Transmitted In The Form Of MMS, SMS, Calls, E-Mails Or An Alarm Receiving Center.',
                'description_bn' => 'Any Alarm Information Is Transmitted In The Form Of MMS, SMS, Calls, E-Mails Or An Alarm Receiving Center. Any Alarm Information Is Transmitted In The Form Of MMS, SMS, Calls, E-Mails Or An Alarm Receiving Center.',
                'image' => 'assetlite/images/ecarrer/general_section/6ii6kL8ujyra3FtZOGr4r9ilQfQCWmcacUi3O2NT.jpeg',
                'video' => NULL,
                'alt_text' => 'Alter text',
                'alt_links' => NULL,
                'call_to_action' => NULL,
                'additional_info' => '{"testimonial_info": {"university_bn": "University bangla", "university_en": "University"}}',
                'is_active' => 1,
                'is_default' => 0,
                'created_at' => '2020-02-13 13:11:39',
                'updated_at' => '2020-02-13 13:11:39',
                'deleted_at' => NULL,
            ),
            43 => 
            array (
                'id' => 44,
                'ecarrer_portals_id' => 2,
                'title_en' => 'Non harum sapiente s',
                'title_bn' => 'Inventore rerum in n',
                'description_en' => 'To Be A Pioneer; Working At The Frontier To Unlock New Opportunities For Customers As They Navigate The Digital World.To Be A Pioneer; Working At The Frontier To Unlock New Opportunities For Customers.',
                'description_bn' => 'To Be A Pioneer; Working At The Frontier To Unlock New Opportunities For Customers As They Navigate The Digital World.To Be A Pioneer; Working At The Frontier To Unlock New Opportunities For Customers.',
                'image' => 'assetlite/images/ecarrer/general_section/5mHMYTjoewZet6dERsx8ibmmmfrw38FYCwRmexLd.jpeg',
                'video' => NULL,
                'alt_text' => 'Vel dolor omnis mole',
                'alt_links' => NULL,
                'call_to_action' => 'a:1:{s:8:"button_1";a:3:{s:8:"label_en";s:10:"Amar offer";s:8:"label_bn";s:10:"Amar offer";s:4:"link";s:51:"http://assetlite.brainstation-23.net/en/amar-offers";}}',
                'additional_info' => NULL,
                'is_active' => 1,
                'is_default' => 0,
                'created_at' => '2020-02-17 05:04:57',
                'updated_at' => '2020-02-24 08:25:06',
                'deleted_at' => '2020-02-24 08:25:06',
            ),
            44 => 
            array (
                'id' => 45,
                'ecarrer_portals_id' => 19,
                'title_en' => 'asd',
                'title_bn' => 'asd',
                'description_en' => 'To Be A Pioneer; Working At The Frontier To Unlock New Opportunities For Customers As They Navigate The Digital World.To Be A Pioneer; Working At The Frontier To Unlock New Opportunities For Customers.',
                'description_bn' => 'To Be A Pioneer; Working At The Frontier To Unlock New Opportunities For Customers As They Navigate The Digital World.To Be A Pioneer; Working At The Frontier To Unlock New Opportunities For Customers.',
                'image' => 'assetlite/images/ecarrer/general_section/TOz00kLgV8es3oNa5dt7MLMLLCWYRv4J7g5MUIbi.jpeg',
                'video' => NULL,
                'alt_text' => 'test',
                'alt_links' => NULL,
                'call_to_action' => NULL,
                'additional_info' => NULL,
                'is_active' => 1,
                'is_default' => 0,
                'created_at' => '2020-02-17 06:35:45',
                'updated_at' => '2020-02-24 08:25:11',
                'deleted_at' => '2020-02-24 08:25:11',
            ),
            45 => 
            array (
                'id' => 46,
                'ecarrer_portals_id' => 21,
                'title_en' => 'Ennovators',
                'title_bn' => 'এনভাটোরস',
                'description_en' => 'Banglalink, In Collaboration With Bangladesh Hi-Tech Park Authority',
                'description_bn' => 'বাংলালিংক, বাংলাদেশ হাই-টেক পার্ক কর্তৃপক্ষের সহযোগিতায়',
                'image' => 'assetlite/images/ecarrer/general_section/u6ZrO6BhhdqrhksdHL2WQDZ7SlkRR2BOldkScmvF.jpeg',
                'video' => NULL,
                'alt_text' => 'test',
                'alt_links' => NULL,
                'call_to_action' => NULL,
                'additional_info' => NULL,
                'is_active' => 0,
                'is_default' => 0,
                'created_at' => '2020-02-17 07:03:39',
                'updated_at' => '2020-02-24 08:29:49',
                'deleted_at' => '2020-02-24 08:29:49',
            ),
            46 => 
            array (
                'id' => 47,
                'ecarrer_portals_id' => 21,
                'title_en' => 'Vacancy',
                'title_bn' => 'কর্মখালি',
                'description_en' => 'Banglalink, In Collaboration With Bangladesh Hi-Tech Park Authority',
                'description_bn' => 'বাংলালিংক, বাংলাদেশ হাই-টেক পার্ক কর্তৃপক্ষের সহযোগিতায়',
                'image' => 'assetlite/images/ecarrer/general_section/iZtI7UbD5qtmMFP8oPtkccbqdJ0LzAeezZHGc8I7.jpeg',
                'video' => NULL,
                'alt_text' => 'test',
                'alt_links' => NULL,
                'call_to_action' => NULL,
                'additional_info' => NULL,
                'is_active' => 0,
                'is_default' => 0,
                'created_at' => '2020-02-17 07:20:43',
                'updated_at' => '2020-02-24 08:29:49',
                'deleted_at' => '2020-02-24 08:29:49',
            ),
            47 => 
            array (
                'id' => 48,
                'ecarrer_portals_id' => 21,
                'title_en' => 'Test',
                'title_bn' => NULL,
                'description_en' => 'tset',
                'description_bn' => 'test',
                'image' => 'assetlite/images/ecarrer/general_section/rdAoH3XMoGvMeQAts7GhiU4FtvgJvGeo1mfduNuO.jpeg',
                'video' => NULL,
                'alt_text' => 'test',
                'alt_links' => NULL,
                'call_to_action' => NULL,
                'additional_info' => NULL,
                'is_active' => 1,
                'is_default' => 0,
                'created_at' => '2020-02-17 08:22:38',
                'updated_at' => '2020-02-24 08:29:49',
                'deleted_at' => '2020-02-24 08:29:49',
            ),
            48 => 
            array (
                'id' => 49,
                'ecarrer_portals_id' => 21,
                'title_en' => 'Qui fugiat voluptat',
                'title_bn' => 'Consequuntur error i',
                'description_en' => 'Laboris debitis id t',
                'description_bn' => 'In dolore labore et',
                'image' => 'assetlite/images/ecarrer/general_section/IzIRB16uegsp29NAa9gYx4wZFsT5S4GoNVhapELl.png',
                'video' => NULL,
                'alt_text' => 'Odit corrupti proid',
                'alt_links' => NULL,
                'call_to_action' => NULL,
                'additional_info' => NULL,
                'is_active' => 1,
                'is_default' => 0,
                'created_at' => '2020-02-17 08:23:19',
                'updated_at' => '2020-02-24 08:29:49',
                'deleted_at' => '2020-02-24 08:29:49',
            ),
            49 => 
            array (
                'id' => 50,
                'ecarrer_portals_id' => 21,
                'title_en' => 'Vero hic veniam ver',
                'title_bn' => 'Voluptates eaque fug',
                'description_en' => 'Placeat culpa est',
                'description_bn' => 'Excepturi sequi non',
                'image' => 'assetlite/images/ecarrer/general_section/VZh7nfY6wPBTdTlyyDqaluSWNIo1AVXlHHLsreEg.jpeg',
                'video' => NULL,
                'alt_text' => 'Dignissimos quia inc',
                'alt_links' => NULL,
                'call_to_action' => NULL,
                'additional_info' => NULL,
                'is_active' => 1,
                'is_default' => 0,
                'created_at' => '2020-02-17 08:23:40',
                'updated_at' => '2020-02-24 08:29:49',
                'deleted_at' => '2020-02-24 08:29:49',
            ),
            50 => 
            array (
                'id' => 51,
                'ecarrer_portals_id' => 6,
                'title_en' => 'test',
                'title_bn' => 'টেস্ট',
                'description_en' => 'To Be A Pioneer; Working At The Frontier To Unlock New Opportunities For Customers As They Navigate The Digital World.To Be A Pioneer; Working At The Fronti',
                'description_bn' => 'টু আ পাইওনিয়ার; ডিজিটাল ওয়ার্ল্ড নেভিগেট করার সাথে সাথে গ্রাহকদের জন্য নতুন সুযোগগুলি আনলক করতে সীমান্তে কাজ করা Tপ্রিয় হয়ে উঠুন; ফ্রন্টিতে কাজ করা',
                'image' => 'assetlite/images/ecarrer/general_section/WSuLLsw1bIIvUfPMm9jml5TDUtGsHZx3gED6wJk4.png',
                'video' => NULL,
                'alt_text' => 'টেস্ট',
                'alt_links' => NULL,
                'call_to_action' => NULL,
                'additional_info' => NULL,
                'is_active' => 1,
                'is_default' => 0,
                'created_at' => '2020-02-17 09:22:26',
                'updated_at' => '2020-02-17 09:28:07',
                'deleted_at' => '2020-02-17 09:28:07',
            ),
            51 => 
            array (
                'id' => 52,
                'ecarrer_portals_id' => 13,
                'title_en' => 'ins',
                'title_bn' => NULL,
                'description_en' => NULL,
                'description_bn' => NULL,
                'image' => 'assetlite/images/ecarrer/general_section/jHH25gLp3SsxV5RwZxJhvSDwseimR0A0dJ3JPPRq.png',
                'video' => NULL,
                'alt_text' => 'ins',
                'alt_links' => 'ins',
                'call_to_action' => NULL,
                'additional_info' => NULL,
                'is_active' => 1,
                'is_default' => 0,
                'created_at' => '2020-02-17 10:21:33',
                'updated_at' => '2020-02-17 10:21:55',
                'deleted_at' => '2020-02-17 10:21:55',
            ),
            52 => 
            array (
                'id' => 53,
                'ecarrer_portals_id' => 13,
                'title_en' => 'qwe',
                'title_bn' => NULL,
                'description_en' => NULL,
                'description_bn' => NULL,
                'image' => 'assetlite/images/ecarrer/general_section/i2x0tVTMgOg3hjvYoA0XvsUPnsGFNPK0ynunN9h6.png',
                'video' => NULL,
                'alt_text' => 'qwe',
                'alt_links' => 'https://www.instagram.com/accounts/login/?hl=en',
                'call_to_action' => NULL,
                'additional_info' => NULL,
                'is_active' => 1,
                'is_default' => 0,
                'created_at' => '2020-02-17 10:26:12',
                'updated_at' => '2020-02-17 10:32:06',
                'deleted_at' => NULL,
            ),
            53 => 
            array (
                'id' => 54,
                'ecarrer_portals_id' => 48,
                'title_en' => 'Title Of The News 02',
                'title_bn' => 'Title Of The News 02 Bangla',
                'description_en' => 'To Be A Pioneer; Working At The Frontier To Unlock New Opportunities For Customers As They Navigate The Digital World.To Be A Pioneer; Working At The Frontier To Unlock New Opportunities For Customers.',
                'description_bn' => 'To Be A Pioneer; Working At The Frontier To Unlock New Opportunities For Customers As They Navigate The Digital World.To Be A Pioneer; Working At The Frontier To Unlock New Opportunities For Customers.',
                'image' => 'assetlite/images/ecarrer/general_section/Mc7saXuQ3j1XCpiu0PxedxLusYS3tFTuJI15wbgl.jpeg',
                'video' => NULL,
                'alt_text' => NULL,
                'alt_links' => NULL,
                'call_to_action' => 'a:2:{s:8:"button_1";a:3:{s:8:"label_en";s:9:"Apply Now";s:8:"label_bn";s:16:"Apply Now Bangla";s:4:"link";s:1:"#";}s:8:"button_2";a:3:{s:8:"label_en";s:3:"FAQ";s:8:"label_bn";s:10:"FAQ Bangla";s:4:"link";s:1:"#";}}',
                'additional_info' => NULL,
                'is_active' => 1,
                'is_default' => 0,
                'created_at' => '2020-02-18 07:00:00',
                'updated_at' => '2020-02-24 09:02:58',
                'deleted_at' => NULL,
            ),
            54 => 
            array (
                'id' => 55,
                'ecarrer_portals_id' => 49,
                'title_en' => 'Title Goes Here',
                'title_bn' => 'Title Goes Here',
                'description_en' => 'Any Alarm Information Is Transmitted In The Form Of MMS, SMS, Calls, E-Mails Or An Alarm Receiving Center. Any Alarm Information Is Transmitted In The Form Of MMS, SMS, Calls, E-Mails Or An Alarm Receiving Center.',
                'description_bn' => 'Any Alarm Information Is Transmitted In The Form Of MMS, SMS, Calls, E-Mails Or An Alarm Receiving Center. Any Alarm Information Is Transmitted In The Form Of MMS, SMS, Calls, E-Mails Or An Alarm Receiving Center.',
                'image' => 'assetlite/images/ecarrer/general_section/4uu3hZqIm5xjix0DlorcMHp5vhiPcFWkQkyVG8ue.png',
                'video' => NULL,
                'alt_text' => 'Alter text',
                'alt_links' => NULL,
                'call_to_action' => NULL,
                'additional_info' => NULL,
                'is_active' => 1,
                'is_default' => 0,
                'created_at' => '2020-02-19 04:19:47',
                'updated_at' => '2020-02-19 04:19:47',
                'deleted_at' => NULL,
            ),
            55 => 
            array (
                'id' => 56,
                'ecarrer_portals_id' => 49,
                'title_en' => 'Title Goes Here',
                'title_bn' => 'Title Goes Here',
                'description_en' => 'Any Alarm Information Is Transmitted In The Form Of MMS, SMS, Calls, E-Mails Or An Alarm Receiving Center. Any Alarm Information Is Transmitted In The Form Of MMS, SMS, Calls, E-Mails Or An Alarm Receiving Center.',
                'description_bn' => 'Any Alarm Information Is Transmitted In The Form Of MMS, SMS, Calls, E-Mails Or An Alarm Receiving Center. Any Alarm Information Is Transmitted In The Form Of MMS, SMS, Calls, E-Mails Or An Alarm Receiving Center.',
                'image' => 'assetlite/images/ecarrer/general_section/tVLZRdrwoUpTj3M2TLXz5Zn4NMPsAN0qRnHTcetj.png',
                'video' => NULL,
                'alt_text' => 'Alter text',
                'alt_links' => NULL,
                'call_to_action' => NULL,
                'additional_info' => NULL,
                'is_active' => 1,
                'is_default' => 0,
                'created_at' => '2020-02-19 04:20:10',
                'updated_at' => '2020-02-19 04:20:10',
                'deleted_at' => NULL,
            ),
            56 => 
            array (
                'id' => 57,
                'ecarrer_portals_id' => 49,
                'title_en' => 'Title Goes Here',
                'title_bn' => 'Title Goes Here',
                'description_en' => 'Any Alarm Information Is Transmitted In The Form Of MMS, SMS, Calls, E-Mails Or An Alarm Receiving Center. Any Alarm Information Is Transmitted In The Form Of MMS, SMS, Calls, E-Mails Or An Alarm Receiving Center.',
                'description_bn' => 'Any Alarm Information Is Transmitted In The Form Of MMS, SMS, Calls, E-Mails Or An Alarm Receiving Center. Any Alarm Information Is Transmitted In The Form Of MMS, SMS, Calls, E-Mails Or An Alarm Receiving Center.',
                'image' => 'assetlite/images/ecarrer/general_section/PxH885iB2b018JBUCQD0z0kMO5MdGrShJSkPzZOI.png',
                'video' => NULL,
                'alt_text' => 'Alter text',
                'alt_links' => NULL,
                'call_to_action' => NULL,
                'additional_info' => NULL,
                'is_active' => 1,
                'is_default' => 0,
                'created_at' => '2020-02-19 04:20:26',
                'updated_at' => '2020-02-19 04:20:26',
                'deleted_at' => NULL,
            ),
            57 => 
            array (
                'id' => 58,
                'ecarrer_portals_id' => 49,
                'title_en' => 'Title Goes Here',
                'title_bn' => 'Title Goes Here',
                'description_en' => 'Any Alarm Information Is Transmitted In The Form Of MMS, SMS, Calls, E-Mails Or An Alarm Receiving Center. Any Alarm Information Is Transmitted In The Form Of MMS, SMS, Calls, E-Mails Or An Alarm Receiving Center.',
                'description_bn' => 'Any Alarm Information Is Transmitted In The Form Of MMS, SMS, Calls, E-Mails Or An Alarm Receiving Center. Any Alarm Information Is Transmitted In The Form Of MMS, SMS, Calls, E-Mails Or An Alarm Receiving Center.',
                'image' => 'assetlite/images/ecarrer/general_section/OMIcWSgQlRIhBWwzjj1jz99AGIDXcERuNbjc3WLV.png',
                'video' => NULL,
                'alt_text' => 'Alter text',
                'alt_links' => NULL,
                'call_to_action' => NULL,
                'additional_info' => NULL,
                'is_active' => 1,
                'is_default' => 0,
                'created_at' => '2020-02-19 04:20:40',
                'updated_at' => '2020-02-19 04:20:40',
                'deleted_at' => NULL,
            ),
            58 => 
            array (
                'id' => 59,
                'ecarrer_portals_id' => 50,
                'title_en' => 'Image 1',
                'title_bn' => NULL,
                'description_en' => NULL,
                'description_bn' => NULL,
                'image' => 'assetlite/images/ecarrer/general_section/GxdBB8wZ00NNAZJ8O2cESvbXXkpXdx8UNTEhOPqk.png',
                'video' => NULL,
                'alt_text' => 'Alter text',
                'alt_links' => NULL,
                'call_to_action' => NULL,
                'additional_info' => NULL,
                'is_active' => 1,
                'is_default' => 0,
                'created_at' => '2020-02-19 04:22:09',
                'updated_at' => '2020-02-24 09:06:23',
                'deleted_at' => NULL,
            ),
            59 => 
            array (
                'id' => 60,
                'ecarrer_portals_id' => 50,
                'title_en' => 'Image 2',
                'title_bn' => NULL,
                'description_en' => NULL,
                'description_bn' => NULL,
                'image' => 'assetlite/images/ecarrer/general_section/l4RswKaP25OodPThMvkQjWuHv6e3XdQCjQpWLZB2.png',
                'video' => NULL,
                'alt_text' => 'Alter text',
                'alt_links' => NULL,
                'call_to_action' => NULL,
                'additional_info' => NULL,
                'is_active' => 1,
                'is_default' => 0,
                'created_at' => '2020-02-19 04:22:25',
                'updated_at' => '2020-02-24 09:06:31',
                'deleted_at' => NULL,
            ),
            60 => 
            array (
                'id' => 61,
                'ecarrer_portals_id' => 50,
                'title_en' => 'Image 3',
                'title_bn' => NULL,
                'description_en' => NULL,
                'description_bn' => NULL,
                'image' => 'assetlite/images/ecarrer/general_section/9BCEzRRp7PXwAwVNNC5Vxg23wXKfmbtrcjibEH7r.png',
                'video' => NULL,
                'alt_text' => 'Alter text',
                'alt_links' => NULL,
                'call_to_action' => NULL,
                'additional_info' => NULL,
                'is_active' => 1,
                'is_default' => 0,
                'created_at' => '2020-02-19 04:22:39',
                'updated_at' => '2020-02-19 04:22:39',
                'deleted_at' => NULL,
            ),
            61 => 
            array (
                'id' => 62,
                'ecarrer_portals_id' => 50,
                'title_en' => 'Image 4',
                'title_bn' => NULL,
                'description_en' => NULL,
                'description_bn' => NULL,
                'image' => 'assetlite/images/ecarrer/general_section/Rvx8x1gNxZEGoNAprnWoKXKeQwtuMJTaotDqthXL.png',
                'video' => NULL,
                'alt_text' => 'Alter text',
                'alt_links' => NULL,
                'call_to_action' => NULL,
                'additional_info' => NULL,
                'is_active' => 1,
                'is_default' => 0,
                'created_at' => '2020-02-19 04:22:55',
                'updated_at' => '2020-02-19 04:22:55',
                'deleted_at' => NULL,
            ),
            62 => 
            array (
                'id' => 63,
                'ecarrer_portals_id' => 51,
                'title_en' => 'Title Of The News 02',
                'title_bn' => 'Title Of The News 02',
                'description_en' => 'To Be A Pioneer; Working At The Frontier To Unlock New Opportunities For Customers As They Navigate The Digital World.To Be A Pioneer; Working At The Frontier To Unlock New Opportunities For Customers.',
                'description_bn' => 'To Be A Pioneer; Working At The Frontier To Unlock New Opportunities For Customers As They Navigate The Digital World.To Be A Pioneer; Working At The Frontier To Unlock New Opportunities For Customers.',
                'image' => 'assetlite/images/ecarrer/general_section/F1WvgFKU7rOvT7jEaM0GaatnsoJSv0Perw2Hxd6b.jpeg',
                'video' => NULL,
                'alt_text' => 'Alter text',
                'alt_links' => NULL,
                'call_to_action' => 'a:2:{s:8:"button_1";a:3:{s:8:"label_en";s:9:"Apply Now";s:8:"label_bn";s:9:"Apply Now";s:4:"link";s:1:"#";}s:8:"button_2";a:3:{s:8:"label_en";s:3:"FAQ";s:8:"label_bn";s:3:"FAQ";s:4:"link";s:1:"#";}}',
                'additional_info' => NULL,
                'is_active' => 1,
                'is_default' => 0,
                'created_at' => '2020-02-19 04:25:23',
                'updated_at' => '2020-02-19 04:25:23',
                'deleted_at' => NULL,
            ),
            63 => 
            array (
                'id' => 64,
                'ecarrer_portals_id' => 52,
                'title_en' => 'Title Goes Here',
                'title_bn' => 'Title Goes Here',
                'description_en' => 'Any Alarm Information Is Transmitted In The Form Of MMS, SMS, Calls, E-Mails Or An Alarm Receiving Center. Any Alarm Information Is Transmitted In The Form Of MMS, SMS, Calls, E-Mails Or An Alarm Receiving Center.',
                'description_bn' => 'Any Alarm Information Is Transmitted In The Form Of MMS, SMS, Calls, E-Mails Or An Alarm Receiving Center. Any Alarm Information Is Transmitted In The Form Of MMS, SMS, Calls, E-Mails Or An Alarm Receiving Center.',
                'image' => 'assetlite/images/ecarrer/general_section/GAs8whlKhRKlcqFJK34mrkulmfck15oUa1gAgFjE.png',
                'video' => NULL,
                'alt_text' => 'Alter text',
                'alt_links' => NULL,
                'call_to_action' => NULL,
                'additional_info' => NULL,
                'is_active' => 1,
                'is_default' => 0,
                'created_at' => '2020-02-19 04:26:58',
                'updated_at' => '2020-02-19 04:26:58',
                'deleted_at' => NULL,
            ),
            64 => 
            array (
                'id' => 65,
                'ecarrer_portals_id' => 52,
                'title_en' => 'Title Goes Here',
                'title_bn' => 'Title Goes Here',
                'description_en' => 'Any Alarm Information Is Transmitted In The Form Of MMS, SMS, Calls, E-Mails Or An Alarm Receiving Center. Any Alarm Information Is Transmitted In The Form Of MMS, SMS, Calls, E-Mails Or An Alarm Receiving Center.',
                'description_bn' => 'Any Alarm Information Is Transmitted In The Form Of MMS, SMS, Calls, E-Mails Or An Alarm Receiving Center. Any Alarm Information Is Transmitted In The Form Of MMS, SMS, Calls, E-Mails Or An Alarm Receiving Center.',
                'image' => 'assetlite/images/ecarrer/general_section/mWxBQvtv1iCQ8zeFSNF1igmEBTs21ScYNKTLzvD0.png',
                'video' => NULL,
                'alt_text' => 'Alter text',
                'alt_links' => NULL,
                'call_to_action' => NULL,
                'additional_info' => NULL,
                'is_active' => 1,
                'is_default' => 0,
                'created_at' => '2020-02-19 04:27:13',
                'updated_at' => '2020-02-19 04:27:13',
                'deleted_at' => NULL,
            ),
            65 => 
            array (
                'id' => 66,
                'ecarrer_portals_id' => 52,
                'title_en' => 'Title Goes Here',
                'title_bn' => 'Title Goes Here',
                'description_en' => 'Any Alarm Information Is Transmitted In The Form Of MMS, SMS, Calls, E-Mails Or An Alarm Receiving Center. Any Alarm Information Is Transmitted In The Form Of MMS, SMS, Calls, E-Mails Or An Alarm Receiving Center.',
                'description_bn' => 'Any Alarm Information Is Transmitted In The Form Of MMS, SMS, Calls, E-Mails Or An Alarm Receiving Center. Any Alarm Information Is Transmitted In The Form Of MMS, SMS, Calls, E-Mails Or An Alarm Receiving Center.',
                'image' => 'assetlite/images/ecarrer/general_section/5iX94cDzkrRfVYYGFNdug6LQBZlqqlU92UgypiWg.png',
                'video' => NULL,
                'alt_text' => 'Alter text',
                'alt_links' => NULL,
                'call_to_action' => NULL,
                'additional_info' => NULL,
                'is_active' => 1,
                'is_default' => 0,
                'created_at' => '2020-02-19 04:27:29',
                'updated_at' => '2020-02-19 04:27:29',
                'deleted_at' => NULL,
            ),
            66 => 
            array (
                'id' => 67,
                'ecarrer_portals_id' => 52,
                'title_en' => 'Title Goes Here',
                'title_bn' => 'Title Goes Here',
                'description_en' => 'To Be A Pioneer; Working At The Frontier To Unlock New Opportunities For Customers As They Navigate The Digital World.To Be A Pioneer; Working At The Frontier To Unlock New Opportunities For Customers.',
                'description_bn' => 'To Be A Pioneer; Working At The Frontier To Unlock New Opportunities For Customers As They Navigate The Digital World.To Be A Pioneer; Working At The Frontier To Unlock New Opportunities For Customers.',
                'image' => 'assetlite/images/ecarrer/general_section/DKDz1DKe3ZZ0fHN8ABiSLNoyIZHTGBep5KN3GMXW.png',
                'video' => NULL,
                'alt_text' => 'Alter text',
                'alt_links' => NULL,
                'call_to_action' => NULL,
                'additional_info' => NULL,
                'is_active' => 1,
                'is_default' => 0,
                'created_at' => '2020-02-19 04:27:50',
                'updated_at' => '2020-02-19 04:27:50',
                'deleted_at' => NULL,
            ),
            67 => 
            array (
                'id' => 68,
                'ecarrer_portals_id' => 53,
                'title_en' => 'Image 1',
                'title_bn' => NULL,
                'description_en' => NULL,
                'description_bn' => NULL,
                'image' => 'assetlite/images/ecarrer/general_section/mYcmrNoKebNywtVwPvgYaqrVbUj6QTJFIOePfKec.png',
                'video' => NULL,
                'alt_text' => 'Alter text',
                'alt_links' => NULL,
                'call_to_action' => NULL,
                'additional_info' => NULL,
                'is_active' => 1,
                'is_default' => 0,
                'created_at' => '2020-02-19 04:29:07',
                'updated_at' => '2020-02-19 04:29:07',
                'deleted_at' => NULL,
            ),
            68 => 
            array (
                'id' => 69,
                'ecarrer_portals_id' => 53,
                'title_en' => 'Image 2',
                'title_bn' => NULL,
                'description_en' => NULL,
                'description_bn' => NULL,
                'image' => 'assetlite/images/ecarrer/general_section/QLIHneWDnSZJEKCQHUjYqRpe5VRKoxqfW2AVJpsw.png',
                'video' => NULL,
                'alt_text' => 'Alter text',
                'alt_links' => NULL,
                'call_to_action' => NULL,
                'additional_info' => NULL,
                'is_active' => 1,
                'is_default' => 0,
                'created_at' => '2020-02-19 04:29:22',
                'updated_at' => '2020-02-24 09:08:37',
                'deleted_at' => NULL,
            ),
            69 => 
            array (
                'id' => 70,
                'ecarrer_portals_id' => 53,
                'title_en' => 'Image 3',
                'title_bn' => NULL,
                'description_en' => NULL,
                'description_bn' => NULL,
                'image' => 'assetlite/images/ecarrer/general_section/5ncDqLqT7jKmxONnGZ8XOnxzq8I1Hke6nrLFv7cq.png',
                'video' => NULL,
                'alt_text' => NULL,
                'alt_links' => NULL,
                'call_to_action' => NULL,
                'additional_info' => NULL,
                'is_active' => 1,
                'is_default' => 0,
                'created_at' => '2020-02-19 04:29:48',
                'updated_at' => '2020-02-19 04:29:48',
                'deleted_at' => NULL,
            ),
            70 => 
            array (
                'id' => 71,
                'ecarrer_portals_id' => 53,
                'title_en' => 'Image 4',
                'title_bn' => NULL,
                'description_en' => NULL,
                'description_bn' => NULL,
                'image' => 'assetlite/images/ecarrer/general_section/xqGfgw4mSLiSPd1fB574edvbqdF0U0EKe71BKfKC.png',
                'video' => NULL,
                'alt_text' => 'Alter text',
                'alt_links' => NULL,
                'call_to_action' => NULL,
                'additional_info' => NULL,
                'is_active' => 1,
                'is_default' => 0,
                'created_at' => '2020-02-19 04:30:01',
                'updated_at' => '2020-02-19 04:30:01',
                'deleted_at' => NULL,
            ),
            71 => 
            array (
                'id' => 72,
                'ecarrer_portals_id' => 54,
                'title_en' => 'title of the News',
                'title_bn' => 'title of the News',
                'description_en' => 'All Banglalink subscribers are eligible for availing the service User will be charged for mobile data as per subscribed data plan',
                'description_bn' => 'All Banglalink subscribers are eligible for availing the service User will be charged for mobile data as per subscribed data plan',
                'image' => 'assetlite/images/ecarrer/general_section/0mHFtaxWsnrIdUHOAeyvuFPFFK1QfS8FHBQobLGG.jpeg',
                'video' => NULL,
                'alt_text' => 'Alter text',
                'alt_links' => NULL,
                'call_to_action' => NULL,
                'additional_info' => NULL,
                'is_active' => 1,
                'is_default' => 0,
                'created_at' => '2020-02-19 05:08:00',
                'updated_at' => '2020-02-19 05:08:00',
                'deleted_at' => NULL,
            ),
            72 => 
            array (
                'id' => 73,
                'ecarrer_portals_id' => 54,
                'title_en' => 'Title Goes Here',
                'title_bn' => 'Title Goes Here',
                'description_en' => 'All Banglalink subscribers are eligible for availing the service User will be charged for mobile data as per subscribed data plan',
                'description_bn' => 'All Banglalink subscribers are eligible for availing the service User will be charged for mobile data as per subscribed data plan',
                'image' => 'assetlite/images/ecarrer/general_section/vsPhh9gYMfHBN25RX5MJK9C6PFGvvMbmZWJj7MLH.jpeg',
                'video' => NULL,
                'alt_text' => 'Alter text',
                'alt_links' => NULL,
                'call_to_action' => NULL,
                'additional_info' => NULL,
                'is_active' => 1,
                'is_default' => 0,
                'created_at' => '2020-02-19 05:08:35',
                'updated_at' => '2020-02-19 05:08:35',
                'deleted_at' => NULL,
            ),
            73 => 
            array (
                'id' => 74,
                'ecarrer_portals_id' => 55,
                'title_en' => 'Image 1',
                'title_bn' => NULL,
                'description_en' => NULL,
                'description_bn' => NULL,
                'image' => 'assetlite/images/ecarrer/general_section/HzmlNsUedJc0yLUjCYYtLgWDLmSQgB5x4VwRtbSM.jpeg',
                'video' => NULL,
                'alt_text' => NULL,
                'alt_links' => NULL,
                'call_to_action' => NULL,
                'additional_info' => NULL,
                'is_active' => 1,
                'is_default' => 0,
                'created_at' => '2020-02-19 05:10:27',
                'updated_at' => '2020-02-19 05:10:27',
                'deleted_at' => NULL,
            ),
            74 => 
            array (
                'id' => 75,
                'ecarrer_portals_id' => 55,
                'title_en' => 'Image 2',
                'title_bn' => NULL,
                'description_en' => NULL,
                'description_bn' => NULL,
                'image' => 'assetlite/images/ecarrer/general_section/kIYEWhLq5mrE7XYQsSD1FQtBXBGsjFSWfSiKLIQj.jpeg',
                'video' => NULL,
                'alt_text' => 'Alter text',
                'alt_links' => NULL,
                'call_to_action' => NULL,
                'additional_info' => NULL,
                'is_active' => 1,
                'is_default' => 0,
                'created_at' => '2020-02-19 05:10:44',
                'updated_at' => '2020-02-19 05:10:44',
                'deleted_at' => NULL,
            ),
            75 => 
            array (
                'id' => 76,
                'ecarrer_portals_id' => 57,
                'title_en' => 'Excepteur deserunt i',
                'title_bn' => 'Amet ad et sunt del',
                'description_en' => 'Exercitation quas lo',
                'description_bn' => 'Facilis qui enim eni',
                'image' => 'assetlite/images/ecarrer/general_section/abOko6fjhzcmJBh8Mc5YuqOLmQXNC9I9FP9u90go.jpeg',
                'video' => NULL,
                'alt_text' => 'Aut eum eiusmod et i',
                'alt_links' => NULL,
                'call_to_action' => NULL,
                'additional_info' => '{"testimonial_info": {"university_bn": "Totam quo quaerat no", "university_en": "Accusantium nulla qu"}}',
                'is_active' => 0,
                'is_default' => 0,
                'created_at' => '2020-02-20 05:51:04',
                'updated_at' => '2020-02-24 09:18:43',
                'deleted_at' => '2020-02-24 09:18:43',
            ),
            76 => 
            array (
                'id' => 77,
                'ecarrer_portals_id' => 2,
                'title_en' => 'Rerum eius quo et qu',
                'title_bn' => 'Dicta quis est susci',
                'description_en' => 'Quia corporis in nob',
                'description_bn' => 'Vitae minima consequ',
                'image' => 'assetlite/images/ecarrer/general_section/Z4IGhOhpGXL00IigXLjXsG7FMGdDnKxUQ7gH3dln.jpeg',
                'video' => NULL,
                'alt_text' => 'Sunt voluptatem vol',
                'alt_links' => NULL,
                'call_to_action' => 'a:1:{s:8:"button_1";a:3:{s:8:"label_en";s:19:"Sit sequi minim iur";s:8:"label_bn";s:20:"Vel numquam ut vitae";s:4:"link";s:19:"Eum est veniam offi";}}',
                'additional_info' => NULL,
                'is_active' => 0,
                'is_default' => 0,
                'created_at' => '2020-02-20 08:31:06',
                'updated_at' => '2020-02-24 08:25:06',
                'deleted_at' => '2020-02-24 08:25:06',
            ),
            77 => 
            array (
                'id' => 78,
                'ecarrer_portals_id' => 34,
                'title_en' => 'Image 3',
                'title_bn' => NULL,
                'description_en' => NULL,
                'description_bn' => NULL,
                'image' => 'assetlite/images/ecarrer/general_section/5bepqrdHe0yBaBC5bxzAo45QXF6OIdKaGAvJJQNb.png',
                'video' => NULL,
                'alt_text' => NULL,
                'alt_links' => NULL,
                'call_to_action' => NULL,
                'additional_info' => NULL,
                'is_active' => 1,
                'is_default' => 0,
                'created_at' => '2020-02-24 09:07:44',
                'updated_at' => '2020-02-24 09:07:44',
                'deleted_at' => NULL,
            ),
            78 => 
            array (
                'id' => 79,
                'ecarrer_portals_id' => 34,
                'title_en' => 'Image 4',
                'title_bn' => NULL,
                'description_en' => NULL,
                'description_bn' => NULL,
                'image' => 'assetlite/images/ecarrer/general_section/uEpVAzbMgFCx74MS4KcKQ52v09B4ejpO300ccJz5.png',
                'video' => NULL,
                'alt_text' => NULL,
                'alt_links' => NULL,
                'call_to_action' => NULL,
                'additional_info' => NULL,
                'is_active' => 1,
                'is_default' => 0,
                'created_at' => '2020-02-24 09:07:58',
                'updated_at' => '2020-02-24 09:08:05',
                'deleted_at' => NULL,
            ),
        ));
        
        
    }
}