<?php

use App\Models\PartnerArea;
use Illuminate\Database\Seeder;

class PartnerAreaSeeder extends Seeder {

    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run() {
        
        PartnerArea::truncate();
        
        $partnerAreaEn = [
            "Dhaka",
            "Bagerhat",
            "Bandarban",
            "Barguna",
            "Barisal",
            "Bhola",
            "Bogra",
            "Brahmanbaria",
            "Chandpur",
            "Chapainababganj",
            "Chittagong",
            "Chuadanga",
            "Comilla",
            "Cox's Bazar",
            "Dinajpur",
            "Faridpur",
            "Feni",
            "Gaibandha",
            "Gazipur",
            "Gopalganj",
            "Habiganj",
            "Jamalpur",
            "Jessore",
            "Jhalokati",
            "Jhenaidah",
            "Joypurhat",
            "Khagrachhari",
            "Khulna",
            "Kishoregonj",
            "Kurigram",
            "Kushtia",
            "Lakshmipur",
            "Lalmonirhat",
            "Madaripur",
            "Magura",
            "Manikganj",
            "Maulvibazar",
            "Meherpur",
            "Munshiganj",
            "Mymensingh",
            "Naogaon",
            "Narail",
            "Narayanganj",
            "Narsingdi",
            "Natore",
            "Netrakona",
            "Nilphamari",
            "Noakhali",
            "Pabna",
            "Panchagarh",
            "Patuakhali",
            "Pirojpur",
            "Rajbari",
            "Rajshahi",
            "Rangamati",
            "Rangpur",
            "Satkhira",
            "Shariatpur",
            "Sherpur",
            "Sirajganj",
            "Sunamganj",
            "Sylhet",
            "Tangail",
            "Thakurgaon",
            "Voirob",
        ];
    $partnerAreaVn = [
        
"ঢাকা",
"বাগেরহাট",
"বান্দরবান",
"বরগুনা",
"বরিশাল",
"ভোলা",
"বগুড়া",
"ব্রাহ্মণবাড়িয়া",
"চাঁদপুর",
"চাঁপাইনবাবগঞ্জ",
"চট্টগ্রাম",
"চুয়াডাঙ্গা",
"কুমিল্লা",
"কক্সবাজার",
"দিনাজপুর",
"ফরিদপুর",
"ফেনী",
"গাইবান্ধা",
"গাজীপুর",
"গোপালগঞ্জ",
"হবিগঞ্জ",
"জামালপুর",
"যশোর",
"ঝালকাঠি",
"ঝিনাইদহে",
"জয়পুরহাট",
"খাগড়াছড়ি",
"খুলনা",
"কিশোরগঞ্জ",
"কুড়িগ্রাম",
"কুষ্টিয়া",
"লক্ষ্মীপুর",
"লালমনিরহাট",
"মাদারীপুর",
"মাগুরা",
"মানিকগঞ্জ",
"মৌলভীবাজার",
"মেহেরপুর",
"মুন্সিগঞ্জ",
"ময়মনসিংহ",
"নওগাঁ",
"নড়াইল",
"নারায়ণগঞ্জ",
"নরসিংদী",
"নাটোর",
"নেত্রকোনা",
"নীলফামারী",
"নোয়াখালী",
"পাবনা",
"পঞ্চগড়",
"পটুয়াখালী",
"পিরোজপুর",
"রাজবাড়ী",
"রাজশাহী",
"রাঙ্গামাটি",
"রংপুর",
"সাতক্ষীরা",
"শরীয়তপুর",
"শেরপুর",
"সিরাজগঞ্জ",
"সুনামগঞ্জ",
"সিলেট",
"টাঙ্গাইল",
"ঠাকুরগাঁও",
"ভৈরব",
    ];

        foreach ($partnerAreaEn as $key => $value) {
            PartnerArea::create([
                'area_en' => $value,
                'area_bn' => $partnerAreaVn[$key]
            ]);
        }
    }

}
