<?php

use Illuminate\Database\Seeder;
use App\Models\SimCategory;
use App\Models\OfferCategory;
use App\Models\Product;
use App\Models\ProductDetail;
use App\Models\DurationCategory;


class ProductsTableSeeder extends Seeder
{

    public function prepaidPlan($packages)
    {
        $days = [1, 3, 7, 15, 30];
        $validityDays = $days[array_rand($days)];

        $rate = [1, 10];
        $ratePaisa = $rate[array_rand($rate)];

        if ($packages == 5) {
            return [
                'callrate_offer' => $ratePaisa,
                'sms_rate_offer' => $ratePaisa,
                'package_offer_type_id' => 5
            ];
        } else {
            return [
                'callrate_offer' => $ratePaisa,
                'internet_offer_mb' => rand(1024, 3072),
                'minute_offer' => rand(100, 500),
                'validity_days' => $validityDays,
                'callrate_short_note_en' => "*Including all",
                'callrate_short_note_bn' => "*সব সহ",
                'gb_short_note_en' => "* Up To 12 GB",
                'gb_short_note_bn' => "* ১২ জিবি পর্যন্ত",
                'balance_check' => '*' . rand(1000, 8888) . '*' . '1#',
                'package_offer_type_id' => 6
            ];
        }

    }


    public function getOfferInfo($name)
    {
        $days = [1, 3, 7, 15, 30];
        $validityDays = $days[array_rand($days)];

        $packageId = [5, 6];
        $packages = $packageId[array_rand($packageId)];

        $durationCategory = DurationCategory::where('days', $validityDays)->first()->id;

        $obj = [];
        switch ($name) {
            case 'internet':
                $obj = [
                    'internet_volume_mb' => 512 * rand(1, 20),
                    'validity_days' => $validityDays,
                    'inspiration_quote_en' => 'Most Popular',
                    'inspiration_quote_bn' => 'সবচেয়ে জনপ্রিয়',
                    'duration_category_id' => $durationCategory
                ];
                break;

            case 'voice':
                $obj = [
                    'minute_volume' => 512 * rand(1, 20),
                    'validity_days' => $validityDays,
                    'inspiration_quote_en' => 'Most Popular',
                    'inspiration_quote_bn' => 'সবচেয়ে জনপ্রিয়',
                    'duration_category_id' => $durationCategory
                ];
                break;

            case 'packages':

                $obj = $this->prepaidPlan($packages);

                break;

            case 'bundles':
                $obj = [
                    'minute_volume' => rand(100, 1000),
                    'internet_volume_mb' => '250',
                    'sms_volume' => '150',
                    'validity_days' => '60',
                    'inspiration_quote_en' => 'Most Popular',
                    'inspiration_quote_bn' => 'সবচেয়ে জনপ্রিয়',
                ];

                break;

            case 'others':
                $obj = [
                    'other_offer_type_id' => 12,
                    'description' => 'Life will be much easier now,
                                      because Banglalink is introducing balance transfer service! Easily
                                      transfer credit to your friends and family who use Banglalink number,
                                      anytime you want.'
                ];

                break;

            case 'startup':
                $obj = [
                    'callrate_offer' => '1',
                    'callrate_short_note__en' => '*Including all',
                    'callrate_short_note_bn' => '* সব সহ',
                    'internet_offer_mb' => '300',
                    'minute_offer' => '450',
                    'sms_offer' => '170',
                    'validity_days' => '90',
                ];

                break;

            case 'business':
                break;
        }

        return $obj;
    }


    public function showInHome($offerType)
    {
        if (in_array($offerType, ['internet', 'voice', 'bundles'])) {
            return rand(0, 2) ? 1 : 0;
        }

        return 0;
    }

    public function getDurationCategory($offerType)
    {
        // return parent::__invoke(); // TODO: Change the autogenerated stub
    }


    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $countHomePageOffer = 0;

        /** Loop For PostPaid Product Create */
        for ($i = 0; $i < 20; $i++) {
            $offer = OfferCategory::whereIn('alias', ['internet', 'packages', 'others'])->inRandomOrder()->first();

            $offerInfo = $this->getOfferInfo($offer->alias);

            $showInHome = $this->showInHome($offer->alias);
            $displayOrder = $showInHome ? ++$countHomePageOffer : 0;

            $postpaidProduct = factory(Product::class)->create(
                [
                    'code' => 'ABC' . $i,
                    'name_en' => 'ABC' . $i,
                    'name_bn' => 'ABC' . $i,
                    'price_tk' => rand(10, 100),
                    'ussd_en' => '*' . rand(1000, 9999) . '*' . '1#',
                    'sim_category_id' => SimCategory::where('alias', 'postpaid')->first('id'),
                    'offer_category_id' => $offer->id,
                    'show_in_home' => $showInHome,
                    'display_order' => $displayOrder,
                    'offer_info' => $offerInfo
                ]
            );

            ProductDetail::create([
                'product_id' => $postpaidProduct->id
            ]);
        }

        /** Loop For PrePaid Product Create */

        for ($i = 0; $i < 30; $i++) {
            $offer = OfferCategory::inRandomOrder()->first();
            $offerInfo = $this->getOfferInfo($offer->alias);

            $showInHome = $this->showInHome($offer->alias);
            $displayOrder = $showInHome ? ++$countHomePageOffer : 0;

            $prePaidProduct = factory(Product::class)->create(
                [
                    'code' => 'ABC' . $i,
                    'name_en' => 'ABC' . $i,
                    'name_bn' => 'ABC' . $i,
                    'price_tk' => rand(10, 100),
                    'ussd_en' => '*' . rand(1000, 9999) . '*' . '1#',
                    'sim_category_id' => SimCategory::where('alias', 'prepaid')->first('id'),
                    'offer_category_id' => $offer->id,
                    'show_in_home' => $showInHome,
                    'display_order' => $displayOrder,
                    'offer_info' => $offerInfo,
                ]
            );

            ProductDetail::create([
                'product_id' => $prePaidProduct->id
            ]);

        }
    }
}



