stages:
    - triggers

.job_template: &template
    tags:
        - bl-devops

prod_deploy:
  stage: triggers
  trigger:
    include: deploy/prod_deploy.yml
    #strategy: depend
  rules:
    - if: $branch == "master"

stg_deploy:
  stage: triggers
  trigger:
    include: deploy/stg_deploy.yml
    #strategy: depend
  rules:
    - if: $branch == "develop"

pre_release_final_deploy:
  stage: triggers
  trigger:
    include: deploy/pre-release-final
    #strategy: depend
  rules:
    - if: $branch == "pre-release-final"
