stages:
    - triggers

.job_template: &template
    tags:
        - bl-devops

prod_deploy:
  stage: triggers
  trigger:
    include: deploy/prod_deploy.yml
    #strategy: depend
  rules:
    - if: $branch == "master"

stg_deploy:
  stage: triggers
  trigger:
    include: deploy/stg_deploy.yml
    #strategy: depend
  rules:
    - if: $branch == "develop"
