<?php

return [
    'mybl' => [
        'columns' => [
            'sim_type'              => 0,
            'content_type'          => 1,
            'product_code'          => 2,
            'renew_product_code'    => 3,
            'recharge_product_code' => 4,
            'name'                  => 5,
            'commercial_name_en'    => 6,
            'commercial_name_bn'    => 7,
            'short_description'     => 8,
            'activation_ussd'       => 9,
            'balance_check_ussd'    => 10,
            'sms_volume'            => 11,
            'minute_volume'         => 12,
            'data_volume'           => 13,
            'internet_volume_mb'    => 13,
            'data_volume_unit'      => 14,
            'validity'              => 15,
            'validity_unit'         => 16,
            'mrp_price'             => 17,
            'price'                 => 18,
            'vat'                   => 19,
            'show_recharge_offer'   => 20,
            'is_rate_cutter_offer'  => 21,
            'offer_section_title'   => 22,
            'tag'                   => 23,
            'call_rate'             => 24,
            'call_rate_unit'        => 25,
            'display_sd_vat_tax'    => 26,
            'display_title_en'      => 27,
            'display_title_bn'      => 28,
            'points'                => 29,
            'is_visible'            => 30,
            'show_from'             => 31,
            'hide_from'             => 32,
            'status'                => 33,
            'name_bn'               => 34,
            'show_timer'            => 35,
            'activation_type'       => 36,
            'cta_name_en'           => 37,
            'cta_name_bn'           => 38,
            'cta_bgd_color'         => 39,
            'cta_text_color'        => 40,
            'redirection_name_en'   => 41,
            'redirection_name_bn'   => 42,
            'redirection_deeplink'  => 43,
            'service_tags'          => 44,
            'lms_tier_slab' => 46,
        ],
        'download-columns' => [
            'sim_type'              => 0,
            'content_type'          => 1,
            'product_code'          => 2,
            'renew_product_code'    => 3,
            'recharge_product_code' => 4,
            'name'                  => 5,
            'commercial_name_en'    => 6,
            'commercial_name_bn'    => 7,
            'short_description'     => 8,
            'activation_ussd'       => 9,
            'balance_check_ussd'    => 10,
            'sms_volume'            => 11,
            'minute_volume'         => 12,
            'data_volume'           => 13,
            'internet_volume_mb'    => 13,
            'data_volume_unit'      => 14,
            'validity'              => 15,
            'validity_unit'         => 16,
            'mrp_price'             => 17,
            'price'                 => 18,
            'vat'                   => 19,
            'show_recharge_offer'   => 20,
            'is_rate_cutter_offer'  => 21,
            'offer_section_title'   => 22,
            'tag'                   => 23,
            'call_rate'             => 24,
            'call_rate_unit'        => 25,
            'display_sd_vat_tax'    => 26,
            'display_title_en'      => 27,
            'display_title_bn'      => 28,
            'points'                => 29,
            'is_visible'            => 30,
            'show_from'             => 31,
            'hide_from'             => 32,
            'Active'                => 33,
            'name_bn'               => 34,
            'show_timer'            => 35,
            'activation_type'       => 36,
            'cta_name_en'           => 37,
            'cta_name_bn'           => 38,
            'cta_bgd_color'         => 39,
            'cta_text_color'        => 40,
            'redirection_name_en'   => 41,
            'redirection_name_bn'   => 42,
            'redirection_deeplink'  => 43,
            'service_tags'          => 44,
            'deep_link'             => 45,
            'lms_tier_slab' => 46,
        ],
        'product_schedule_statuses' => [
            0 => 'None',
            1 => 'Active Schedule',
            2 => 'To be Hidden',
            3 => 'Completed Schedule',
            4 => 'To be Shown'
        ],
        'max_no_of_pin_to_top' => 150
    ],
    /*'pcat' => [
        'columns' => [
            'content_type'          => 10,
            'product_code'          => 4,
            'name'                  => 1,
            'commercial_name_en'    => 2,
            'commercial_name_bn'    => 3,
            'activation_ussd'       =>
            'balance_check_ussd'    =>
            'sms_volume'            =>
            'minute_volume'         =>
            'data_volume'           =>
            'internet_volume_mb'    =>
            'data_volume_unit'      =>
            'validity'              =>
            'validity_unit'         =>
            'mrp_price'             =>
            'price'                 =>
            'vat'                   =>
            'show_recharge_offer'   =>
            'is_rate_cutter_offer'  =>
            'offer_section_title'   =>
            'tag'                   =>
            'call_rate'             =>
            'call_rate_unit'        =>
            'status'                =>
            'validity_in_days'      =>
        ]
    ],*/
    'assetlite' => [
        'columns' => [
            'sim_type'             => 0,
            'content_type'         => 1,
//            'family_name'          => 2,
            'product_code'         => 2,
            'recharge_product_code' => 3,
            'renew_product_code'   => 4,
            'name'                 => 5,
            'commercial_name_en'   => 6,
            'commercial_name_bn'   => 7,
            'short_description'    => 8,
            'activation_ussd'      => 9,
            'balance_check_ussd'   => 10,
//            'offer_id'             => 12,
            'sms_volume'           => 11,
            'minute_volume'        => 12,
            'data_volume'          => 13,
            'internet_volume_mb'   => 13,
            'data_volume_unit'     => 14,
            'validity'             => 15,
            'validity_in_days'     => 15,
            'validity_unit'        => 16,
            'mrp_price'            => 17,
            'price'                => 18,
            'vat'                  => 19,
            'is_amar_offer'        => 20,
//            'is_auto_renewable'    => 23,
//            'is_recharge_offer'    => 24,
//            'is_gift_offer'        => 25,
            'rate_cutter_offer'    => 21,
            'rate_cutter_unit'     => 22,
            'assetlite_offer_type' => 23,
            'short_text'           => 24,
            'sms_rate_unit'        => 25,
//            'validity_in_days'     => 31,
        ]
    ],
    'mybl_plan' => [
        'columns' => [
            'sim_type'              => 0,
            'content_type'          => 1,
            'product_code'          => 2,
            'renew_product_code'    => 3,
            'recharge_product_code' => 4,
            'sms_volume'            => 5,
            'minute_volume'         => 6,
            'data_volume'           => 7,
            'data_volume_unit'      => 8,
            'validity'              => 9,
            'validity_unit'         => 10,
            'tag'                   => 11,
            'display_sd_vat_tax_en' => 12,
            'display_sd_vat_tax_bn' => 13,
            'points'                => 14,
            'market_price'          => 15,
            'discount_price'        => 16,
            'discount_percentage'   => 17,
            'savings_amount'        => 18,
            'is_active'             => 19,
        ]
    ],
    // Website My Plan
    'my_plan' => [
        'columns' => [
            'sim_type'              => 0,
            'content_type'          => 1,
            'product_code'          => 2,
            'renew_product_code'    => 3,
            'recharge_product_code' => 4,
            'sms_volume'            => 5,
            'minute_volume'         => 6,
            'data_volume'           => 7,
            'data_volume_unit'      => 8,
            'validity'              => 9,
            'validity_unit'         => 10,
            'tag'                   => 11,
            'display_sd_vat_tax_en' => 12,
            'display_sd_vat_tax_bn' => 13,
            'points'                => 14,
            'market_price'          => 15,
            'discount_price'        => 16,
            'discount_percentage'   => 17,
            'savings_amount'        => 18,
            'is_active'             => 19,
        ]
    ]
];
