<?php

return [
    'mybl' => [
        'columns' => [
            'sim_type'              => 0,
            'content_type'          => 1,
            'family_name'           => 2,
            'product_code'          => 3,
            'renew_product_code'    => 4,
            'recharge_product_code' => 5,
            'name'                  => 6,
            'commercial_name_en'    => 7,
            'commercial_name_bn'    => 8,
            'short_description'     => 9,
            'activation_ussd'       => 10,
            'balance_check_ussd'    => 11,
            'offer_id'              => 12,
            'sms_volume'            => 13,
            'minute_volume'         => 14,
            'data_volume'           => 15,
            'internet_volume_mb'    => 15,
            'data_volume_unit'      => 16,
            'validity'              => 17,
            'validity_unit'         => 18,
            'mrp_price'             => 19,
            'price'                 => 20,
            'vat'                   => 21,
            'is_amar_offer'         => 22,
            'is_auto_renewable'     => 23,
            'is_recharge_offer'     => 24,
            'is_rate_cutter_offer'  => 25,
            'offer_section_title'   => 26,
            'tag'                   => 27,
            'validity_in_days'      => 28,
        ]
    ],
    'assetlite' => [
        'columns' => [
            'sim_type'             => 0,
            'content_type'         => 1,
            'family_name'          => 2,
            'product_code'         => 3,
            'name'                 => 4,
            'commercial_name_en'   => 5,
            'commercial_name_bn'   => 6,
            'short_description'    => 7,
            'activation_ussd'      => 8,
            'balance_check_ussd'   => 9,
            'offer_id'             => 10,
            'sms_volume'           => 11,
            'minute_volume'        => 12,
            'data_volume'          => 13,
            'internet_volume_mb'   => 13,
            'data_volume_unit'     => 14,
            'validity'             => 15,
            'validity_unit'        => 16,
            'mrp_price'            => 17,
            'price'                => 18,
            'vat'                  => 19,
            'is_amar_offer'        => 20,
            'is_auto_renewable'    => 21,
            'is_recharge_offer'    => 22,
            'is_gift_offer'        => 23,
            'is_social_pack'       => 24,
            'assetlite_offer_type' => 25,
            'validity_in_days'     => 26,

        ]
    ]
];
